# SPDX-License-Identifier: MIT
"""Generate src/world.inc (the sea, its row table and the sites) from tests/world.py.

usage: make_world.py [--check]
The sea is 32 rows of 16 bytes: 4-bit cells, two per byte, the even column
in the high bits. as_rows holds the address of each row.
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import world  # noqa: E402

OUT = HERE.parent / 'src/world.inc'


def render() -> str:
    lines = ['; SPDX-License-Identifier: MIT',
             '; Generated by tests/make_world.py from tests/world.py. Do not edit.',
             '; Upstream jr100dev games/abyss_signal/world.json.',
             'as_rows:']
    for start in range(0, 32, 8):
        lines.append('        .dw     ' + ', '.join(f'as_sea + {16 * r}' for r in range(start, start + 8)))
    lines.append('as_sea:')
    for row in world.MAP:
        values = [int(c, 16) for c in row]
        lines.append('        .db     ' + ', '.join(str(values[i] << 4 | values[i + 1])
                                                  for i in range(0, 32, 2)))
    lines.append('as_site_x:')
    lines.append('        .db     ' + ', '.join(str(x) for _, x, _ in world.SITES))
    lines.append('as_site_y:')
    lines.append('        .db     ' + ', '.join(str(y) for _, _, y in world.SITES))
    lines.append('as_site_names:')
    lines.append('        .dw     ' + ', '.join(f'as_site_{i}' for i in range(6)))
    for i, (name, _, _) in enumerate(world.SITES):
        lines.append(f'as_site_{i}:')
        lines.append(f'        .db     "{name}", 0')
    lines.append('as_site_5:')
    lines.append('        .db     "SURFACE BASE", 0')
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    text = render()
    if '--check' in sys.argv:
        if OUT.read_text() != text:
            raise SystemExit(f'{OUT} is out of date')
    else:
        OUT.write_text(text)
