# SPDX-License-Identifier: BSD-3-Clause
"""Machine-independent model of sdk/selftest.inc (fixtures and input scripts).

Game models implement reset(), init(), act(action), tick() and state_bytes()
and list their RAM layout as LAYOUT: (name, length) in order from GAME_STATE,
where length 1 is a plain field and longer entries are lists. A model with a
held direction keeps it in the attribute `held`.

A fixture is (name, level, operation, {field or (list, index): value}); the
operation is 'tick', ('act', a) or ('held', h). A script is a list of
(wait, operation) entries with operation ('act', a) or ('held', h); see
sdk/selftest.inc for the timing.
"""
from __future__ import annotations

from port_model import PortModel, PLAY


def offsets(layout):
    table, at = {}, 0
    for name, length in layout:
        table[name] = at
        at += length
    return table, at


def op_byte(op) -> int:
    if op == 'tick':
        return 0
    kind, value = op
    return value if kind == 'act' else 0x80 | value


def fixture_pairs(layout, values):
    table, _ = offsets(layout)
    pairs = []
    for key, value in values.items():
        if isinstance(key, tuple):
            pairs.append((table[key[0]] + key[1], value))
        else:
            pairs.append((table[key], value))
    return pairs


def fixture_include(prefix, layout, fixtures, scripts) -> str:
    """The assembly tables (game_fixtures, game_scripts) for src/selftest.inc."""
    lines = ['; SPDX-License-Identifier: MIT',
             '; Generated by tests/make_selftest.py from tests/selftest.py. Do not edit.',
             '; Fixtures: level, operation, pair count, (state offset, value) pairs; 0xFF ends.',
             'game_fixtures:']
    for name, level, op, values in fixtures:
        pairs = fixture_pairs(layout, values)
        data = [level, op_byte(op), len(pairs)] + [b for pair in pairs for b in pair]
        lines.append(f'        .db     {", ".join(str(v) for v in data)}   ; {name}')
    lines.append('        .db     0xff')
    lines.append('; Scripts: (wait, operation) entries per stage; 0xFF ends.')
    lines.append('game_scripts:')
    lines.append('        .dw     ' + ', '.join(f'{prefix}_script_{i}' for i in range(len(scripts))))
    for i, script in enumerate(scripts):
        lines.append(f'{prefix}_script_{i}:')
        data = [b for wait, op in script for b in (wait, op_byte(op))] + [0xff]
        for start in range(0, len(data), 16):
            lines.append('        .db     ' + ', '.join(str(v) for v in data[start:start + 16]))
    return '\n'.join(lines) + '\n'


class SelfTest:
    def __init__(self, make_game, levels: int, layout, size: int, limit: int):
        self.make_game = make_game
        self.levels = levels
        self.layout = layout
        self.size = size
        self.limit = limit

    def start(self, level):
        game = self.make_game()
        port = PortModel(game, self.levels, False)
        port.level = level
        port.new_level()
        return game, port

    def snapshot(self, game, port) -> bytes:
        return bytes.fromhex(game.state_bytes())[:self.size] + bytes([port.mode])

    def apply(self, game, op) -> None:
        if op == 'tick':
            game.tick()
        elif op[0] == 'act':
            game.act(op[1])
        else:
            game.held = op[1]
            game.tick()

    def fixture(self, level, op, values):
        game, port = self.start(level)
        table, _ = offsets(self.layout)
        for key, value in values.items():
            if isinstance(key, tuple):
                getattr(game, key[0])[key[1]] = value
            else:
                setattr(game, key, value)
        self.apply(game, op)
        return game, port

    def fixtures_bytes(self, fixtures) -> bytes:
        out = b''
        for _, level, op, values in fixtures:
            game, port = self.fixture(level, op, values)
            out += self.snapshot(game, port)
        return out

    def play(self, level, script, limit=None):
        """Mirror of jr_test_stage: returns (game, port, ticks)."""
        limit = self.limit if limit is None else limit
        game, port = self.start(level)
        entries = list(script)
        at = 0
        wait = entries[0][0] if entries else None
        ticks = 0
        while True:
            # jr_test_script_due
            while at < len(entries):
                if wait:
                    wait -= 1
                    break
                op = entries[at][1]
                at += 1
                wait = entries[at][0] if at < len(entries) else None
                if op[0] == 'held':
                    game.held = op[1]
                else:
                    game.act(op[1])
                    if port.mode != PLAY:
                        break
            if port.mode != PLAY:
                break
            game.tick()
            ticks += 1
            if port.mode != PLAY or ticks == limit:
                break
        return game, port, ticks

    def scripts_bytes(self, scripts) -> bytes:
        out = b''
        for level, script in enumerate(scripts):
            game, port, ticks = self.play(level, script)
            out += self.snapshot(game, port) + bytes([ticks >> 8, ticks & 0xff])
        return out
