# SPDX-License-Identifier: MIT
"""Generate src/rooms.inc (packed room maps) from tests/levels.py.

usage: make_rooms.py [--check]
Each room is 27 bytes: 108 cells of 2 bits (0 floor, 1 wall, 2 target,
3 exit), four cells per byte, the first cell in the high bits.
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from levels import LEVELS  # noqa: E402

OUT = HERE.parent / 'src/rooms.inc'


def render() -> str:
    lines = ['; SPDX-License-Identifier: MIT',
             '; Generated by tests/make_rooms.py from tests/levels.py. Do not edit.',
             '; Upstream jr100dev games/trace_blade/levels.json, 2 bits per cell.',
             'tb_rooms:']
    for name, cells, _ in LEVELS:
        values = ['.#*X'.index(c) for c in cells]
        packed = [values[i] << 6 | values[i + 1] << 4 | values[i + 2] << 2 | values[i + 3]
                  for i in range(0, 108, 4)]
        lines.append(f'        ; {name}')
        for start in range(0, 27, 14):
            lines.append('        .db     ' + ', '.join(str(v) for v in packed[start:start + 14]))
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    text = render()
    if '--check' in sys.argv:
        if OUT.read_text() != text:
            raise SystemExit(f'{OUT} is out of date')
    else:
        OUT.write_text(text)
