# SPDX-License-Identifier: MIT
"""Write src/fixtures.inc from tests/fixtures.py (input and output are fixed).

Usage: python3 games/brick-pulse/tests/make_fixtures.py [--check]
"""
import importlib.util
from pathlib import Path
import sys

HERE = Path(__file__).resolve().parent
OUTPUT = HERE.parent / 'src/fixtures.inc'


def load(name):
    spec = importlib.util.spec_from_file_location('bp_' + name, HERE / f'{name}.py')
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def render():
    fields = load('model').STATE_FIELDS
    lines = ['; SPDX-License-Identifier: MIT',
             '; Generated by tests/make_fixtures.py from tests/fixtures.py. Do not edit.',
             '; level, held, pair count, then (state offset, value) pairs; 0xFF ends.',
             'bp_fixtures:']
    for name, level, held, values, bricks in load('fixtures').FIXTURES:
        pairs = [(index, hits) for index, hits in sorted(bricks.items())]
        pairs += [(24 + fields.index(field), value) for field, value in values.items()]
        data = [level, held, len(pairs)] + [byte for pair in pairs for byte in pair]
        lines.append(f'        .db     {", ".join(str(v) for v in data)}   ; {name}')
    lines.append('        .db     0xff')
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    text = render()
    if '--check' in sys.argv:
        raise SystemExit(0 if OUTPUT.read_text() == text else 'src/fixtures.inc is stale')
    OUTPUT.write_text(text)
    print(f'wrote {OUTPUT}')
