# SPDX-License-Identifier: MIT
"""Generate src/levels.inc (the twenty sectors) from tests/levels.py.

usage: make_levels.py [--check]
Each sector: start x, y, exit x, y, guard count, ammo, par, then per guard
x, y, direction (1 N, 2 S, 3 W, 4 E), then 15 bytes of walls (120 cells,
row by row, the first cell in bit 7), and cb_names points at its name.
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from levels import SECTORS  # noqa: E402

OUT = HERE.parent / 'src/levels.inc'


def cells(rows, chars):
    return [(x, y, c) for y, r in enumerate(rows) for x, c in enumerate(r) if c in chars]


def render() -> str:
    lines = ['; SPDX-License-Identifier: MIT',
             '; Generated by tests/make_levels.py from tests/levels.py. Do not edit.',
             '; Upstream jr100dev games/chrono_breach/levels.json.',
             'cb_sectors:',
             '        .dw     ' + ', '.join(f'cb_sector_{i}' for i in range(len(SECTORS)))]
    for i, (name, ammo, par, rows, _) in enumerate(SECTORS):
        (sx, sy, _), = cells(rows, '@')
        (ex, ey, _), = cells(rows, 'X')
        guards = cells(rows, '^v<>')
        walls = [1 if c == '#' else 0 for r in rows for c in r]
        packed = [sum(walls[b + k] << (7 - k) for k in range(8)) for b in range(0, 120, 8)]
        lines.append(f'cb_sector_{i}:                    ; {name}')
        lines.append(f'        .db     {sx}, {sy}, {ex}, {ey}, {len(guards)}, {ammo}, {par}')
        if guards:
            lines.append('        .db     ' + ', '.join(f'{x}, {y}, {"^v<>".index(c) + 1}'
                                                      for x, y, c in guards))
        lines.append('        .db     ' + ', '.join(str(v) for v in packed))
    lines.append('cb_names:')
    lines.append('        .dw     ' + ', '.join(f'cb_name_{i}' for i in range(len(SECTORS))))
    for i, (name, *_) in enumerate(SECTORS):
        lines.append(f'cb_name_{i}:')
        lines.append(f'        .db     "{name}", 0')
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    text = render()
    if '--check' in sys.argv:
        if OUT.read_text() != text:
            raise SystemExit(f'{OUT} is out of date')
    else:
        OUT.write_text(text)
