# SPDX-License-Identifier: MIT
"""Generate src/data.inc (cards, enemies, monsters, logo and music) from tests/data.py.

usage: make_data.py [--check]
sd_cards holds per card: cost, attack, block, special, value, exhaust.
sd_enemies holds per enemy: hp, attack, guard. A monster is 8 x 8 cells of
the quarter-block PCG codes 0x80-0x8F (bit 0 upper left, 1 upper right,
2 lower left, 3 lower right), as upstream draws its 16 x 16 figures.
The music is this port's three-voice arrangement of upstream music.json:
the upstream line an octave up on channel F, and on channels D and C a
chord part and a bass from the chord of each bar (CHORDS below).
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import data  # noqa: E402

OUT = HERE.parent / 'src/data.inc'
TRIADS = {'Dm': (2, 5, 9), 'F': (5, 9, 0), 'Gm': (7, 10, 2), 'A': (9, 1, 4), 'A7': (9, 1, 7),
          'Bb': (10, 2, 5), 'C': (0, 4, 7)}
CHORDS = {
    'MUSIC_TITLE': ('Dm Dm C F Bb Dm A Dm Dm F C A Bb Dm A Dm '
                    'F Dm Gm C Bb C A Dm Dm F C A Bb A7 Dm Dm').split(),
    'MUSIC_BATTLE': ('Dm Dm Bb Bb F F C A Dm Dm Bb Dm F F C A '
                     'Dm Dm Bb Dm F F A A7 Dm F Bb Dm F C A Dm').split(),
}
LOGO = {
    'S': ['01111', '10000', '10000', '01110', '00001', '00001', '11110'],
    'I': ['11111', '00100', '00100', '00100', '00100', '00100', '11111'],
    'G': ['01111', '10000', '10000', '10011', '10001', '10001', '01111'],
    'L': ['10000', '10000', '10000', '10000', '10000', '10000', '11111'],
    'D': ['11110', '10001', '10001', '10001', '10001', '10001', '11110'],
    'E': ['11111', '10000', '10000', '11110', '10000', '10000', '11111'],
    'C': ['01111', '10000', '10000', '10000', '10000', '10000', '01111'],
    'K': ['10001', '10010', '10100', '11000', '10100', '10010', '10001'],
}


def quads(pixels):
    """Pixel rows (even size) -> quarter-block codes, row by row."""
    return [0x80 + sum(bool(pixels[y + dy][x + dx]) << (dy * 2 + dx)
                       for dy in range(2) for dx in range(2))
            for y in range(0, len(pixels), 2) for x in range(0, len(pixels[0]), 2)]


def logo(word):
    width = len(word) * 6 - 1
    pixels = [[0] * (width + 1) for _ in range(8)]
    for i, ch in enumerate(word):
        for y, line in enumerate(LOGO[ch]):
            for x, bit in enumerate(line):
                pixels[y][i * 6 + x] = bit == '1'
    return (width + 1) // 2, quads(pixels)


def pitch_class_note(pc, base):
    """The note number (1 = C2) of pitch class pc at or above base."""
    note = base + (pc - (base - 1)) % 12
    return note


def voices(name):
    tpe, bars = data.MUSIC[name]
    melody, chords, bass = [], [], []
    for bar, chord in zip(bars, CHORDS[name]):
        for pitch, units in bar:
            melody += [24 + pitch if pitch else 0, units * tpe]
        root, third, fifth = TRIADS[chord]
        span = 8 * tpe
        if tpe >= 15:           # title: a held third, root and fifth in halves
            chords += [pitch_class_note(third, 37), span]
            bass += [pitch_class_note(root, 3), span // 2, pitch_class_note(fifth, 3), span // 2]
        else:                   # battle: chord stabs on the beat, a driving bass
            for i in range(4):
                chords += [pitch_class_note((third, fifth)[i & 1], 37), 2 * tpe - 6, 0, 6]
            low = pitch_class_note(root, 3)
            bass += [low, tpe, low + 12, tpe, pitch_class_note(fifth, 3), tpe, low, tpe] * 2
    return melody, chords, bass


def db(values, width=16):
    return ''.join('        .db     ' + ', '.join(str(v) for v in values[i:i + width]) + '\n'
                   for i in range(0, len(values), width))


def text(label, value):
    return f'{label}:\n        .db     "{value}", 0\n'


def generate():
    out = ['; SPDX-License-Identifier: MIT\n',
           '; Generated by tests/make_data.py from tests/data.py. Do not edit.\n',
           '; Upstream jr100dev games/sigil_deck: cards.json, enemies.json, assets.py\n',
           '; and music.json (1.6.1).\n']
    out.append('sd_cards:\n' + db([v for c in data.CARDS for v in c[1:7]], 6))
    out.append('sd_card_names:\n' + ''.join(f'        .dw     sd_card_name_{i}\n'
                                             for i in range(len(data.CARDS))))
    out.append('sd_card_texts:\n' + ''.join(f'        .dw     sd_card_text_{i}\n'
                                             for i in range(len(data.CARDS))))
    for i, card in enumerate(data.CARDS):
        out.append(text(f'sd_card_name_{i}', card[0]))
        out.append(text(f'sd_card_text_{i}', card[7]))
    out.append('sd_enemies:\n' + db([v for e in data.ENEMIES for v in e[1:]], 3))
    out.append('sd_enemy_names:\n' + ''.join(f'        .dw     sd_enemy_name_{i}\n'
                                              for i in range(len(data.ENEMIES))))
    for i, enemy in enumerate(data.ENEMIES):
        out.append(text(f'sd_enemy_name_{i}', enemy[0]))
    out.append('sd_battle_order:\n' + db(data.BATTLE_ORDER))
    out.append('sd_initial_deck:\n' + db(data.INITIAL_DECK))
    out.append('sd_monsters:\n')
    for figure in data.MONSTERS:
        out.append(db(quads([[c == '#' for c in row] for row in figure]), 8))
    for word in ('SIGIL', 'DECK'):
        width, codes = logo(word)
        out.append(f'sd_logo_{word.lower()}:\n        .db     {width}\n' + db(codes, width))
    for name in data.MUSIC:
        label = 'sd_' + name.lower()
        melody, chords, bass = voices(name)
        out.append(f'{label}:\n        .db     1\n'
                   f'        .dw     {label}_f, {label}_d, {label}_c\n')
        for suffix, track in (('f', melody), ('d', chords), ('c', bass)):
            assert all(0 <= n <= 60 for n in track[::2]) and all(1 <= f <= 255 for f in track[1::2])
            out.append(f'{label}_{suffix}:\n' + db(track + [0, 0]))
    return ''.join(out)


if __name__ == '__main__':
    text_out = generate()
    if sys.argv[1:] == ['--check']:
        if OUT.read_text() != text_out:
            raise SystemExit(f'{OUT} is stale; run tests/make_data.py')
    else:
        OUT.write_text(text_out)
