# SPDX-License-Identifier: MIT
"""Generate src/rooms.inc (chamber maps and names) from tests/rooms.py.

usage: make_rooms.py [--check]
Each chamber is 80 bytes: 160 cells of 4 bits (0 floor, 1 wall, 2 seal,
4 gate, 5 hazard, 6 anchor), two cells per byte, the first in the high bits.
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from rooms import ROOMS  # noqa: E402

OUT = HERE.parent / 'src/rooms.inc'
CODES = {'.': 0, '#': 1, 'S': 2, 'G': 4, 'H': 5, 'A': 6}


def render() -> str:
    lines = ['; SPDX-License-Identifier: MIT',
             '; Generated by tests/make_rooms.py from tests/rooms.py. Do not edit.',
             '; Upstream jr100dev games/loop_ten/rooms.json, 4 bits per cell.',
             'lt_chambers:']
    for name, cells in ROOMS:
        values = [CODES[c] for c in cells]
        packed = [values[i] << 4 | values[i + 1] for i in range(0, 160, 2)]
        lines.append(f'        ; {name}')
        for start in range(0, 80, 16):
            lines.append('        .db     ' + ', '.join(str(v) for v in packed[start:start + 16]))
    lines.append('lt_names:')
    lines.append('        .dw     ' + ', '.join(f'lt_name_{i}' for i in range(len(ROOMS))))
    for i, (name, _) in enumerate(ROOMS):
        lines.append(f'lt_name_{i}:')
        lines.append(f'        .db     "{name}", 0')
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    text = render()
    if '--check' in sys.argv:
        if OUT.read_text() != text:
            raise SystemExit(f'{OUT} is out of date')
    else:
        OUT.write_text(text)
