#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
"""Generate sdk/audio_notes.inc: equal-tempered C2-B6 for the MN1271 channels.

Channel F: 16-bit count, prescaler 1. Channels C/D: 8-bit count with the
prescaler 8 (control 0x0e) when the count fits, else 64 (control 0x16).
Frequency = CPU clock / (count * prescaler * 2), as in the fixed emulator.
Pitch on hardware is unverified.
"""
from __future__ import annotations

import argparse
from pathlib import Path

CLOCK = 1_339_285
NOTES = 60                      # note 1 = C2 (MIDI 36) ... note 60 = B6
OUTPUT = Path(__file__).resolve().parents[1] / 'sdk/audio_notes.inc'
NAMES = ['C', 'CS', 'D', 'DS', 'E', 'F', 'FS', 'G', 'GS', 'A', 'AS', 'B']


def frequency(note: int) -> float:
    return 440.0 * 2 ** ((note + 35 - 69) / 12)


def f_count(note: int) -> int:
    return round(CLOCK / 2 / frequency(note))


def cd_entry(note: int) -> tuple[int, int]:
    count = round(CLOCK / 16 / frequency(note))
    if count <= 255:
        return 0x0e, count
    return 0x16, round(CLOCK / 128 / frequency(note))


def emulated(control_prescale: int, count: int) -> int:
    return CLOCK // (count * control_prescale * 2)


def render() -> str:
    lines = ['; SPDX-License-Identifier: BSD-3-Clause',
             '; Generated by tools/audio_notes.py. Do not edit.',
             '; Note numbers for sdk/audio.inc tracks: 0 rest, 1 = C2 ... 60 = B6.', '']
    for note in range(1, NOTES + 1):
        name = NAMES[(note - 1) % 12] + str(2 + (note - 1) // 12)
        lines.append(f'AU_{name + ":":<8}.equ    {note}')
    lines += ['', 'au_f_table:']
    for note in range(1, NOTES + 1):
        lines.append(f'        .dw     {f_count(note)}')
    lines += ['', 'au_cd_table:']
    for note in range(1, NOTES + 1):
        control, count = cd_entry(note)
        lines.append(f'        .db     0x{control:02x}, {count}')
    return '\n'.join(lines) + '\n'


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    text = render()
    if args.check:
        return 0 if OUTPUT.read_text() == text else 1
    OUTPUT.write_text(text)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
