; SPDX-License-Identifier: MIT
; Floor population, full-period RNG, and wall-blocked visibility.
SELECT_FLOOR:
    LDX FLOORS
    STX [FP]
    RTS
RANDOM:
    LDAA [G_RNG + 1]
    LDAB 0x55
    JSR MULTIPLY
    STAB [RANDOM_WORK + 1]
    STAA [RANDOM_WORK]
    LDAA [G_RNG]
    LDAB 0x55
    JSR MULTIPLY
    ADDB [RANDOM_WORK]
    STAB [RANDOM_WORK]
    LDAA [G_RNG + 1]
    LDAB 0x62
    JSR MULTIPLY
    ADDB [RANDOM_WORK]
    STAB [RANDOM_WORK]
    LDAB [RANDOM_WORK + 1]
    LDAA [RANDOM_WORK]
    ADDB ((0x3619) & 255)
    ADCA ((0x3619) >> 8)
    STAB [G_RNG + 1]
    STAA [G_RNG]
    JSR WORD_Z
    RTS
; A compact centered panel stays visible until the new floor is rendered.
GENERATE_WORLD:
    LDX FRAMEBUFFER + 10 * 32 + 8
    LDAA JR200_CHAR_SPACE
    LDAB 16
GEN_PANEL_MARGIN:
    STAA [X]
    STAA [X + 64]
    INX
    DECB
    BNE GEN_PANEL_MARGIN
    LDX S_BUILDING
    LDAB ((FRAMEBUFFER + 11 * 32 + 8) & 255)
    LDAA ((FRAMEBUFFER + 11 * 32 + 8) >> 8)
    JSR TEXT
    JSR PRESENT
    LDAA [G_FLOOR]
    STAA [GEN_FLOOR]
    JSR SELECT_FLOOR
    LDX FLOORS
    CLRA
GEN_ZERO:
    STAA [X]
    INX
    CPX FLOORS + FLOOR_DATA_END
    BNE GEN_ZERO
BUILD_ROOMS:
    JSR TERRAIN_LAYOUT
    INC [0xC273]
    JSR RANDOM
    ANDA 7
    ADDA 12
    TST [G_DIFFICULTY]
    BNE ITEM_COUNT_READY
    ADDA 4
ITEM_COUNT_READY:
    STAA [ITEM_COUNT]
    CLR [PLACE_INDEX]
GEN_RANDOM_ITEM:
    JSR RANDOM
    ANDA 31
    STAA [INDEX_OFFSET + 1]
    LDX ITEM_WEIGHTS
    ADDX16 INDEX_OFFSET
    LDAA [X]
    STAA [PLACE_TYPE]
    JSR PLACE_ITEM
    DEC [ITEM_COUNT]
    BNE GEN_RANDOM_ITEM
    LDAA [G_FLOOR]
    CMPA 3
    BCS GEN_NO_RING
    JSR RANDOM
    ANDA 15
    BNE GEN_NO_RING
    LDAA 21
    STAA [PLACE_TYPE]
    JSR PLACE_ITEM
GEN_NO_RING:
    INC [0xC273]
    LDAA [G_DIFFICULTY]
    ASLA
    ADDA [G_FLOOR]
    ADDA 4
    CMPA MAX_ENEMIES
    BLS POPULATION_READY
    LDAA MAX_ENEMIES
POPULATION_READY:
    STAA [G_ENEMY_COUNT]
    CLR [E_INDEX]
GEN_ENEMY:
    JSR FREE_POSITION
    LDAA [NX]
    SUBA [G_X]
    BPL ARRIVAL_DX
    NEGA
ARRIVAL_DX:
    STAA [TEMP]
    LDAA [NY]
    SUBA [G_Y]
    BPL ARRIVAL_DY
    NEGA
ARRIVAL_DY:
    ADDA [TEMP]
    CMPA 6
    BCS GEN_ENEMY
    JSR ENEMY_POINTER
    LDAA [NX]
    STAA [X]
    LDAA [NY]
    STAA [X + 1]
    LDAA [G_FLOOR]
    ASLA
    ADDA 4
    CMPA 15
    BLS KIND_LIMIT_READY
    LDAA 15
KIND_LIMIT_READY:
    STAA [KIND_LIMIT]
ENEMY_ROLL_KIND:
    JSR RANDOM
    ANDA 15
    CMPA [KIND_LIMIT]
    BCC ENEMY_ROLL_KIND
    TAB
    LDX ENEMY_DISTRIBUTION
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    STAA [CANDIDATE]
    JSR ENEMY_POINTER
    STAA [X + 2]
    LDAB [CANDIDATE]
    DECB
    LDX ENEMY_HP
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    JSR ENEMY_POINTER
    STAA [X + 3]
    LDAA 255
    STAA [X + 4]
    STAA [X + 5]
    INC [E_INDEX]
    LDAA [E_INDEX]
    CMPA [G_ENEMY_COUNT]
    BEQ GEN_ENEMY_DONE
    JMP GEN_ENEMY
GEN_ENEMY_DONE:
    INC [0xC273]
GEN_EXTRAS_READY:
    JSR GENERATE_EXTRAS
    RTS
FREE_POSITION:
    JSR POLL_KEY
    JSR RANDOM
    ANDA 63
    CMPA MAP_WIDTH - 1
    BCC FREE_POSITION
    TSTA
    BEQ FREE_POSITION
    STAA [NX]
    JSR RANDOM
    ANDA 31
    TSTA
    BEQ FREE_POSITION
    CMPA MAP_HEIGHT - 1
    BEQ FREE_POSITION
    STAA [NY]
    TAB
    LDAA [NX]
    JSR CELL
    ANDA 127
    CMPA 1
    BNE FREE_POSITION
    LDAA [NX]
    CMPA [G_X]
    BNE POSITION_NOT_ENTRY
    LDAA [NY]
    CMPA [G_Y]
    BEQ FREE_POSITION
POSITION_NOT_ENTRY:
    JSR FIND_ENEMY
    TSTA
    BNE FREE_POSITION
    JSR FIND_ITEM
    TSTA
    BNE FREE_POSITION
    RTS
PLACE_ITEM:
    JSR FREE_POSITION
    LDAB [PLACE_INDEX]
    LDAA 3
    JSR MULTIPLY
    ADDB [FP + 1]
    ADCA [FP]
    ADDB ((ITEM_START) & 255)
    ADCA ((ITEM_START) >> 8)
    STAB [ITEM_PTR + 1]
    STAA [ITEM_PTR]
    LDX [ITEM_PTR]
    LDAA [NX]
    STAA [X]
    LDAA [NY]
    STAA [X + 1]
    LDAA [PLACE_TYPE]
    STAA [X + 2]
    INC [PLACE_INDEX]
    RTS
FIND_ENEMY:
    LDX ENEMY_START
    LDAB MAX_ENEMIES
FIND_ENEMY_LOOP:
    STX [E_PTR]
    TST [X + 3]
    BEQ FIND_ENEMY_NEXT
    LDAA [X]
    CMPA [NX]
    BNE FIND_ENEMY_NEXT
    LDAA [X + 1]
    CMPA [NY]
    BNE FIND_ENEMY_NEXT
    LDAA [X + 2]
    RTS
FIND_ENEMY_NEXT:
    ADDX8 8
    DECB
    BNE FIND_ENEMY_LOOP
    STX [E_PTR]
    CLRA
    RTS
FIND_ITEM:
    LDX FLOORS + ITEM_START
    STX [ITEM_PTR]
FIND_ITEM_LOOP:
    LDX [ITEM_PTR]
    TST [X + 2]
    BEQ FIND_ITEM_NEXT
    LDAA [X]
    CMPA [NX]
    BNE FIND_ITEM_NEXT
    LDAA [X + 1]
    CMPA [NY]
    BNE FIND_ITEM_NEXT
    LDAA [X + 2]
    RTS
FIND_ITEM_NEXT:
    LDX [ITEM_PTR]
    ADDX8 3
    STX [ITEM_PTR]
    CPX FLOORS + FLOOR_DATA_END
    BNE FIND_ITEM_LOOP
    CLRA
    RTS
ENEMY_POINTER:
    PSHA
    LDAA [E_INDEX]
    ASLA
    ASLA
    ASLA
    STAA [INDEX_OFFSET + 1]
    LDX ENEMY_START
    ADDX16 INDEX_OFFSET
    STX [E_PTR]
    PULA
    RTS
ENSURE_VISIBILITY:
    CLR [NEW_SIGHT]
    TST [VIS_DIRTY]
    BNE UPDATE_VISIBILITY
    LDAA [G_X]
    CMPA [LAST_VIS_X]
    BNE UPDATE_VISIBILITY
    LDAA [G_Y]
    CMPA [LAST_VIS_Y]
    BNE UPDATE_VISIBILITY
    RTS
UPDATE_VISIBILITY:
    JSR POLL_KEY
    CLR [NEW_SIGHT]
    LDAA [G_X]
    STAA [LAST_VIS_X]
    LDAA [G_Y]
    STAA [LAST_VIS_Y]
    CLR [VIS_DIRTY]
    LDX VISIBLE
    CLRA
VIS_CLEAR:
    STAA [X]
    INX
    CPX VISIBLE + MASK_BYTES
    BNE VIS_CLEAR
    LDX FRAMEBUFFER
    LDAA 255
VIS_CACHE_CLEAR:
    STAA [X]
    INX
    CPX FRAMEBUFFER + 176
    BNE VIS_CACHE_CLEAR
    LDX SIGHT_RAYS
VIS_TARGET:
    LDAA [X]
    CMPA 255
    BNE VIS_TARGET_READY
    JMP VIS_DONE
VIS_TARGET_READY:
    INX
    STX [LOS_RAY_PTR]
    STAA [LOS_TARGET]
    CLR [LOS_BLOCKED]
    ANDA 15
    ADDA [G_X]
    SUBA 5
    STAA [LOS_TX]
    CMPA MAP_WIDTH
    BCC VIS_INVALID
    LDAA [LOS_TARGET]
    LSRA
    LSRA
    LSRA
    LSRA
    ADDA [G_Y]
    SUBA 5
    STAA [LOS_TY]
    CMPA MAP_HEIGHT
    BCS VIS_RAY
VIS_INVALID:
    INC [LOS_BLOCKED]
VIS_RAY:
    LDX [LOS_RAY_PTR]
    LDAA [X]
    INX
    STX [LOS_RAY_PTR]
    CMPA 255
    BEQ VIS_RAY_DONE
    TST [LOS_BLOCKED]
    BNE VIS_RAY
    STAA [COL]
    STAA [INDEX_OFFSET + 1]
    LDX FRAMEBUFFER
    ADDX16 INDEX_OFFSET
    LDAA [X]
    CMPA 255
    BNE VIS_SAMPLE_READY
    STX [DRAW]
    LDAA [COL]
    ANDA 15
    ADDA [G_X]
    SUBA 5
    STAA [NX]
    LDAA [COL]
    LSRA
    LSRA
    LSRA
    LSRA
    ADDA [G_Y]
    SUBA 5
    TAB
    LDAA [NX]
    JSR TERRAIN_CELL
    CMPA 5
    BNE VIS_SAMPLE_STORE
    CLRA
VIS_SAMPLE_STORE:
    LDX [DRAW]
    STAA [X]
VIS_SAMPLE_READY:
    TSTA
    BNE VIS_RAY
    INC [LOS_BLOCKED]
    BRA VIS_RAY
VIS_RAY_DONE:
    TST [LOS_BLOCKED]
    BNE VIS_NEXT_TARGET
    LDAA [LOS_TX]
    LDAB [LOS_TY]
    JSR MARK_VISIBLE
    DEC [CELL_BIT_PTR]
    LDX [CELL_BIT_PTR]
    LDAA [X]
    BITA [CELL_MASK]
    BNE VIS_REMEMBER
    INC [NEW_SIGHT]
VIS_REMEMBER:
    JSR MARK_SEEN
VIS_NEXT_TARGET:
    LDX [LOS_RAY_PTR]
    JMP VIS_TARGET
VIS_DONE:
    RTS
