; SPDX-License-Identifier: MIT
; 5 secret wall; 6/7 hidden damage/poison trap; 8/9 revealed trap.
; Secrets only replace existing walls, so the original connected route survives.
GENERATE_EXTRAS:
    CLR [EXTRA_COUNT]
    LDAA 1
    STAA [EXTRA_Y]
SECRET_ROW:
    LDAA 1
    STAA [EXTRA_X]
SECRET_CELL:
    LDAA [EXTRA_X]
    LDAB [EXTRA_Y]
    JSR CELL
    ANDA 15
    BNE SECRET_NEXT
    LDAA [EXTRA_X]
    DECA
    LDAB [EXTRA_Y]
    JSR CELL
    ANDA 15
    CMPA 1
    BNE SECRET_VERTICAL
    LDAA [EXTRA_X]
    INCA
    LDAB [EXTRA_Y]
    JSR CELL
    ANDA 15
    CMPA 1
    BEQ SECRET_CANDIDATE
SECRET_VERTICAL:
    LDAA [EXTRA_X]
    LDAB [EXTRA_Y]
    DECB
    JSR CELL
    ANDA 15
    CMPA 1
    BNE SECRET_NEXT
    LDAA [EXTRA_X]
    LDAB [EXTRA_Y]
    INCB
    JSR CELL
    ANDA 15
    CMPA 1
    BNE SECRET_NEXT
SECRET_CANDIDATE:
    JSR RANDOM
    ANDA 7
    BNE SECRET_NEXT
    LDAA [EXTRA_X]
    LDAB [EXTRA_Y]
    JSR CELL
    LDAA 5
    JSR WRITE_CELL
    INC [EXTRA_COUNT]
    LDAA [EXTRA_COUNT]
    CMPA 2
    BEQ GENERATE_TRAPS
SECRET_NEXT:
    INC [EXTRA_X]
    LDAA [EXTRA_X]
    CMPA MAP_WIDTH - 1
    BNE SECRET_CELL
    INC [EXTRA_Y]
    LDAA [EXTRA_Y]
    CMPA MAP_HEIGHT - 1
    BEQ FAR_EXTRAS_2_0
    JMP SECRET_ROW
FAR_EXTRAS_2_0:
GENERATE_TRAPS:
    LDAA 4
    STAA [EXTRA_COUNT]
GENERATE_TRAP:
    JSR FREE_POSITION
    LDAA [NX]
    LDAB [NY]
    JSR CELL
    LDAA [EXTRA_COUNT]
    ANDA 1
    ADDA 6
    JSR WRITE_CELL
    DEC [EXTRA_COUNT]
    BNE GENERATE_TRAP
    RTS
SEARCH_ACTION:
    CLR [EXTRA_FOUND]
    LDAA [G_Y]
    DECA
    STAA [EXTRA_Y]
SEARCH_ROW:
    LDAA [G_X]
    DECA
    STAA [EXTRA_X]
SEARCH_CELL:
    LDAA [EXTRA_X]
    CMPA MAP_WIDTH
    BCC SEARCH_NEXT
    LDAB [EXTRA_Y]
    CMPB MAP_HEIGHT
    BCC SEARCH_NEXT
    JSR CELL
    ANDA 15
    CMPA 5
    BEQ SEARCH_SECRET
    CMPA 6
    BCS SEARCH_NEXT
    CMPA 7
    BHI SEARCH_NEXT
    ADDA 2
    BRA SEARCH_REVEAL
SEARCH_SECRET:
    LDAA 1
SEARCH_REVEAL:
    JSR WRITE_CELL
    JSR MARK_SEEN
    INC [EXTRA_FOUND]
SEARCH_NEXT:
    INC [EXTRA_X]
    LDAA [EXTRA_X]
    SUBA [G_X]
    CMPA 2
    BNE SEARCH_CELL
    INC [EXTRA_Y]
    LDAA [EXTRA_Y]
    SUBA [G_Y]
    CMPA 2
    BNE SEARCH_ROW
    LDAA 25
    TST [EXTRA_FOUND]
    BEQ SEARCH_MESSAGE
    LDAA 24
SEARCH_MESSAGE:
    STAA [G_MESSAGE]
    JMP COMMIT_TURN
TRIGGER_TRAP:
    LDAA [G_X]
    LDAB [G_Y]
    JSR CELL
    ANDA 15
    CMPA 6
    BCS TRAP_DONE
    CMPA 9
    BHI TRAP_DONE
    ANDA 1
    BNE TRAP_POISON
    LDAA [G_HP]
    SUBA 3
    BHI TRAP_DAMAGE
    CLRA
TRAP_DAMAGE:
    STAA [G_HP]
    BRA TRAP_REMOVE
TRAP_POISON:
    LDAA 6
    STAA [G_POISON]
    CLR [G_POISON_TICK]
TRAP_REMOVE:
    LDAA 1
    JSR WRITE_CELL
    LDAA 26
    STAA [G_MESSAGE]
    CLR [G_AUTOWALK]
TRAP_DONE:
    RTS
