; SPDX-License-Identifier: MIT
; Turn dispatch, difficulty selection, and new adventure state.
NEW_GAME:
    CLR [G_CLEAR_SUNG]
    CLR [G_WAND_SLOT]
    LDX [G_SEED]
    STX [G_RNG]
    LDX G_X
    CLRA
NEW_ZERO:
    STAA [X]
    INX
    CPX G_RNG
    BNE NEW_ZERO
    LDX G_BAG
NEW_BAG_ZERO:
    STAA [X]
    INX
    CPX G_SEED
    BNE NEW_BAG_ZERO
    CLR [G_FLOOR]
    CLR [G_SUSPEND]
    CLR [G_MENU]
    LDX FRAME_READY
    STX [G_READY_ADDRESS]
    LDX 0x5244
    STX [G_MAGIC]
    LDX 0x3031
    STX [G_MAGIC + 2]
    LDAA 3
    STAA [G_ATTACK]
    LDAA 1
    STAA [G_LEVEL]
    CLR [G_POISON]
    CLR [G_POISON_TICK]
    CLR [G_AUTOWALK]
    LDX DIFFICULTY_DEPTH
    LDAB [G_DIFFICULTY]
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    STAA [G_DEPTH]
    LDX DIFFICULTY_HP
    LDAB [G_DIFFICULTY]
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    STAA [G_HP]
    STAA [G_SHOWN_HP]
    STAA [G_MAX_HP]
    LDX DIFFICULTY_FOOD
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    STAA [G_FOOD]
    LDX 0x0001
    STX [G_IDENTITIES]
    LDAA 2
    STAA [G_IDENTITIES + 2]
    LDX 0x0304
    STX [G_IDENTITIES + 3]
    JSR RANDOM
    ANDA 1
    BEQ SHUFFLE_SECOND
    LDX 0x0100
    STX [G_IDENTITIES]
SHUFFLE_SECOND:
    JSR RANDOM
    ANDA 1
    BEQ SHUFFLE_SCROLL
    LDAA [G_IDENTITIES + 1]
    LDAB [G_IDENTITIES + 2]
    STAB [G_IDENTITIES + 1]
    STAA [G_IDENTITIES + 2]
SHUFFLE_SCROLL:
    JSR RANDOM
    ANDA 1
    BEQ SHUFFLE_DONE
    LDX 0x0403
    STX [G_IDENTITIES + 3]
SHUFFLE_DONE:
    LDAA 5
    STAA [G_IDENTITIES + 5]
    LDAA 6
    STAA [G_IDENTITIES + 6]
    LDAA 7
    STAA [G_IDENTITIES + 7]
    JSR RANDOM
    ANDA 3
    TAB
    LDX POTION_SLOTS
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAB [X]
    LDX G_IDENTITIES
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    LDAB [G_IDENTITIES + 5]
    STAB [X]
    STAA [G_IDENTITIES + 5]
    LDAA 6
    STAA [COUNT]
SHUFFLE_NEW_SCROLL:
    JSR RANDOM
    ANDA 3
    TAB
    LDX SCROLL_SLOTS
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAB [X]
    LDX G_IDENTITIES
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    PSHA
    STX [P1]
    LDAB [COUNT]
    LDX G_IDENTITIES
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    PULB
    STAB [X]
    LDX [P1]
    STAA [X]
    INC [COUNT]
    LDAA [COUNT]
    CMPA 8
    BEQ SHUFFLE_SCROLL_DONE
    JMP SHUFFLE_NEW_SCROLL
SHUFFLE_SCROLL_DONE:
    JSR GENERATE_WORLD
    CLR [G_FLOOR]
    JSR SELECT_FLOOR
    LDAA 1
    STAA [G_MODE]
    CLR [G_MESSAGE]
    JSR UPDATE_VISIBILITY
    RTS
REDRAW:
    JSR RENDER_SCREEN
    LDAA [G_HP]
    CMPA [G_SHOWN_HP]
    STAA [G_SHOWN_HP]
    BCC REDRAW_FEEDBACK
    LDX HIT_NOTES
    JSR PLAY_PHRASE
REDRAW_FEEDBACK:
    JSR END_FEEDBACK
    JSR POLL_KEY
FRAME_READY:
    NOP
IDLE:
    JSR POLL_KEY
    TST [G_MODE]
    BNE IDLE_SEED_DONE
    LDAB [G_SEED + 1]
    LDAA [G_SEED]
    ADDB ((1) & 255)
    ADCA ((1) >> 8)
    JSR WORD_Z
    BNE SEED_NONZERO
    ADDB ((1) & 255)
    ADCA ((1) >> 8)
SEED_NONZERO:
    STAB [G_SEED + 1]
    STAA [G_SEED]
    JSR TITLE_SHIMMER
IDLE_SEED_DONE:
    LDAA [G_PENDING]
    BNE DISPATCH
    LDAA [G_MODE]
    CMPA 7
    BEQ FRAME_READY
    TST [G_AUTOWALK]
    BEQ IDLE
    LDAB [G_REPEAT + 1]
    LDAA [G_REPEAT]
    ADDB ((1) & 255)
    ADCA ((1) >> 8)
    STAB [G_REPEAT + 1]
    STAA [G_REPEAT]
    SUBB ((150) & 255)
    SBCA ((150) >> 8)
    BCS IDLE
    CLRA
    CLRB
    STAB [G_REPEAT + 1]
    STAA [G_REPEAT]
    JSR SAFE_WALK
    TST [SAFE_FLAG]
    BNE REPEAT_STEP
    CLR [G_AUTOWALK]
    BRA IDLE
REPEAT_STEP:
    LDAA [G_PREVIOUS]
    STAA [G_KEY]
    JSR WORLD_DIRECTION
    JMP REDRAW
DISPATCH:
    STAA [G_KEY]
    CLR [G_PENDING]
    CLR [G_AUTOWALK]
    CLRA
    CLRB
    STAB [G_REPEAT + 1]
    STAA [G_REPEAT]
    LDAA [G_MODE]
    BEQ TITLE_INPUT
    CMPA 1
    BEQ WORLD_INPUT
    CMPA 5
    BEQ INSPECT_INPUT
    CMPA 7
    BEQ SUSPEND_INPUT
    CMPA 8
    BCS DISPATCH_ACTIVE
    JMP END_INPUT
DISPATCH_ACTIVE:
    JSR MENU_INPUT
    JMP REDRAW
TITLE_INPUT:
    LDAA [G_KEY]
    CMPA 5
    BEQ TITLE_START
    CMPA 1
    BEQ DIFFICULTY_UP
    CMPA 2
    BNE TITLE_DONE
DIFFICULTY_UP:
    LDAA [G_DIFFICULTY]
    LDAB 2
    JSR WRAP_CURSOR
    STAA [G_DIFFICULTY]
TITLE_DONE:
    JMP REDRAW
TITLE_START:
    JSR NEW_GAME
    JSR RENDER_SCREEN
    LDX S_START
    LDAB ((FRAMEBUFFER + 11 * 32 + 11) & 255)
    LDAA ((FRAMEBUFFER + 11 * 32 + 11) >> 8)
    JSR TEXT
    JSR PRESENT
    LDX START_NOTES
    JSR PLAY_PHRASE
TITLE_START_SOUND_DONE:
    JMP REDRAW
WORLD_INPUT:
    LDAA [G_KEY]
    CMPA 5
    BEQ OPEN_MENU
    CMPA 6
    BEQ WORLD_DONE
    CMPA 11
    BEQ WORLD_WAIT
    JSR WORLD_DIRECTION
WORLD_DONE:
    JMP REDRAW
WORLD_WAIT:
    CLR [G_MESSAGE]
    JSR COMMIT_TURN
    JMP REDRAW
OPEN_MENU:
    LDAA 2
    STAA [G_MODE]
    CLR [G_MENU]
    JMP REDRAW
INSPECT_INPUT:
    JSR INSPECT_MOVE
    JMP REDRAW
SUSPEND_INPUT:
    LDAA [G_KEY]
    CMPA 5
    BNE SUSPEND_STAY
    CLR [G_SUSPEND]
    LDAA 1
    STAA [G_MODE]
SUSPEND_STAY:
    JMP REDRAW
END_INPUT:
    LDAA [G_KEY]
    CMPA 5
    BNE END_STAY
    CLR [G_MODE]
END_STAY:
    JMP REDRAW
