; SPDX-License-Identifier: MIT
; Inventory, identification, equipment exchange, and descent.
PICKUP:
    LDAA [G_X]
    STAA [NX]
    LDAA [G_Y]
    STAA [NY]
    TAB
    LDAA [NX]
    JSR CELL
    ANDA 127
    CMPA 4
    BNE PICKUP_ITEM
    LDAA 1
    STAA [G_TREASURE]
    LDAA 9
    STAA [G_MODE]
    CLR [G_SUSPEND]
    LDAA 1
    JSR WRITE_CELL
    LDAA 6
    STAA [G_MESSAGE]
PICKUP_ITEM:
    JSR FIND_ITEM
    TSTA
    BEQ PICKUP_DONE
    CMPA 13
    BEQ PICKUP_GOLD
    STAA [ITEM_TYPE]
    LDX G_BAG
PICKUP_SLOT:
    TST [X]
    BEQ PICKUP_STORE
    INX
    CPX G_BAG + 6
    BNE PICKUP_SLOT
    LDAA 8
    STAA [G_MESSAGE]
    RTS
PICKUP_STORE:
    LDAA [ITEM_TYPE]
    STAA [X]
    LDAA 7
    STAA [G_MESSAGE]
    BRA PICKUP_REMOVE
PICKUP_GOLD:
    LDAA 7
    STAA [G_MESSAGE]
    LDAB [G_GOLD + 1]
    LDAA [G_GOLD]
    ADDB ((10) & 255)
    ADCA ((10) >> 8)
    BCC PICKUP_GOLD_STORE
    LDAB ((0xFFFF) & 255)
    LDAA ((0xFFFF) >> 8)
PICKUP_GOLD_STORE:
    STAB [G_GOLD + 1]
    STAA [G_GOLD]
PICKUP_REMOVE:
    LDX [ITEM_PTR]
    CLR [X + 2]
PICKUP_DONE:
    RTS
DROP_LOCATION:
    LDAA [G_X]
    STAA [NX]
    LDAA [G_Y]
    STAA [NY]
    JSR FIND_ITEM
    TSTA
    BNE DROP_UNAVAILABLE
    LDX FLOORS + ITEM_START
    STX [ITEM_PTR]
DROP_FIND_SLOT:
    LDX [ITEM_PTR]
    TST [X + 2]
    BEQ DROP_AVAILABLE
    LDX [ITEM_PTR]
    ADDX8 3
    STX [ITEM_PTR]
    CPX FLOORS + FLOOR_DATA_END
    BNE DROP_FIND_SLOT
DROP_UNAVAILABLE:
    CLRA
    RTS
DROP_AVAILABLE:
    LDAA 1
    RTS
WRITE_DROP:
    LDX [ITEM_PTR]
    LDAA [G_X]
    STAA [X]
    LDAA [G_Y]
    STAA [X + 1]
    LDAA [CANDIDATE]
    STAA [X + 2]
    RTS
BAG_ITEM:
    LDX G_BAG
    LDAB [G_SLOT]
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    STAA [ITEM_TYPE]
    RTS
USE_ITEM:
    JSR BAG_ITEM
    CMPA 17
    BCS USE_OLD_ITEM
    JMP USE_TOOL
USE_OLD_ITEM:
    CMPA 14
    BCC USE_MAGIC
    CMPA 7
    BCS LONG_I106
    JMP EQUIP_ITEM
LONG_I106:
    CMPA 1
    BNE USE_MAGIC
    LDX DIFFICULTY_RESTORE
    LDAB [G_DIFFICULTY]
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [G_FOOD]
    ADDA [X]
    BCC FOOD_RESTORED
    LDAA 255
FOOD_RESTORED:
    STAA [G_FOOD]
    JMP CONSUME_ITEM
USE_MAGIC:
    JSR MAGIC_INDEX
    LDX BITS
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [G_KNOWN]
    ORAA [X]
    STAA [G_KNOWN]
    LDX G_IDENTITIES
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    STAA [ITEM_EFFECT]
    BEQ HEAL_ITEM
    CMPA 1
    BEQ POISON_ITEM
    CMPA 2
    BEQ STRENGTH_ITEM
    CMPA 3
    BEQ MAP_ITEM
    CMPA 4
    BNE NEW_MAGIC_EFFECT
    JSR TELEPORT_ITEM
    JMP CONSUME_ITEM
NEW_MAGIC_EFFECT:
    JSR EXTENDED_MAGIC
    JMP CONSUME_ITEM
HEAL_ITEM:
    CLR [G_POISON]
    CLR [G_POISON_TICK]
    LDX DIFFICULTY_HEAL
    LDAB [G_DIFFICULTY]
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [G_HP]
    ADDA [X]
    CMPA [G_MAX_HP]
    BLS HEALING_READY
    LDAA [G_MAX_HP]
HEALING_READY:
    STAA [G_HP]
    JMP CONSUME_ITEM
POISON_ITEM:
    LDAA [G_HP]
    SUBA 3
    BHI POISONED_ALIVE
    CLRA
POISONED_ALIVE:
    STAA [G_HP]
    JMP CONSUME_ITEM
STRENGTH_ITEM:
    LDAA 13
    STAA [G_BUFF]
    JMP CONSUME_ITEM
MAP_ITEM:
    LDX SEEN
    LDAA 255
MAP_NEXT:
    STAA [X]
    INX
    CPX SEEN + MASK_BYTES
    BNE MAP_NEXT
CONSUME_ITEM:
    JSR BAG_ITEM
    CLR [X]
    LDAA [G_MENU]
    CMPA 1
    BEQ CONSUMED_DISCARD
    LDAA [ITEM_TYPE]
    CMPA 14
    BCC CONSUMED_MAGIC
    CMPA 7
    BCC CONSUMED_EQUIPMENT
    CMPA 1
    BEQ CONSUMED_FOOD
CONSUMED_MAGIC:
    LDAB [ITEM_EFFECT]
    LDX EFFECT_MESSAGES
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    BRA CONSUMED_MESSAGE
CONSUMED_FOOD:
    LDAA 9
    BRA CONSUMED_MESSAGE
CONSUMED_EQUIPMENT:
    LDAA 22
    BRA CONSUMED_MESSAGE
CONSUMED_DISCARD:
    LDAA 23
CONSUMED_MESSAGE:
    STAA [G_MESSAGE]
    LDAA 1
    STAA [G_MODE]
    JMP COMMIT_TURN
EQUIP_ITEM:
    CMPA 10
    BCC EQUIP_ARMOR
    LDAA [G_WEAPON]
    BRA EQUIP_PREPARE
EQUIP_ARMOR:
    LDAA [G_ARMOR]
EQUIP_PREPARE:
    STAA [CANDIDATE]
    TSTA
    BEQ EQUIP_READY
    JSR DROP_LOCATION
    TSTA
    BNE EQUIP_DROP
    LDAA 10
    STAA [G_MESSAGE]
    RTS
EQUIP_DROP:
    JSR WRITE_DROP
EQUIP_READY:
    LDAA [ITEM_TYPE]
    CMPA 10
    BCC ARMOR_READY
    STAA [G_WEAPON]
    SUBA 3
    STAA [G_ATTACK]
    JMP CONSUME_ITEM
ARMOR_READY:
    STAA [G_ARMOR]
    SUBA 9
    STAA [G_DEFENSE]
    JMP CONSUME_ITEM
DISCARD_ITEM:
    JSR BAG_ITEM
    CMPA 22
    BNE DISCARD_NOT_WORN
    DECA
DISCARD_NOT_WORN:
    STAA [CANDIDATE]
    JSR DROP_LOCATION
    TSTA
    BNE DISCARD_READY
    LDAA 10
    STAA [G_MESSAGE]
    RTS
DISCARD_READY:
    JSR WRITE_DROP
    JMP CONSUME_ITEM
TELEPORT_ITEM:
    CLR [CHECK_X]
    CLR [CHECK_Y]
TELEPORT_SCAN:
    LDAA [CHECK_X]
    STAA [NX]
    LDAB [CHECK_Y]
    STAB [NY]
    JSR CELL
    CMPA 129
    BNE TELEPORT_NEXT
    JSR FIND_ITEM
    TSTA
    BNE TELEPORT_NEXT
    JSR FIND_ENEMY
    TSTA
    BNE TELEPORT_NEXT
    CLR [E_INDEX]
TELEPORT_ENEMY:
    JSR ENEMY_POINTER
    TST [X + 3]
    BEQ TELEPORT_ENEMY_NEXT
    LDAA [X]
    SUBA [NX]
    BPL TELEPORT_DX
    NEGA
TELEPORT_DX:
    STAA [TEMP]
    LDAA [X + 1]
    SUBA [NY]
    BPL TELEPORT_DY
    NEGA
TELEPORT_DY:
    ADDA [TEMP]
    CMPA 1
    BLS TELEPORT_NEXT
TELEPORT_ENEMY_NEXT:
    INC [E_INDEX]
    LDAA [E_INDEX]
    CMPA MAX_ENEMIES
    BNE TELEPORT_ENEMY
    LDAA [NX]
    STAA [G_X]
    LDAA [NY]
    STAA [G_Y]
    RTS
TELEPORT_NEXT:
    INC [CHECK_X]
    LDAA [CHECK_X]
    CMPA MAP_WIDTH
    BNE TELEPORT_SCAN
    CLR [CHECK_X]
    INC [CHECK_Y]
    LDAA [CHECK_Y]
    CMPA MAP_HEIGHT
    BNE TELEPORT_SCAN
    RTS
STAIRS_ACTION:
    LDAA [G_X]
    LDAB [G_Y]
    JSR CELL
    ANDA 127
    CMPA 3
    BNE STAIRS_DONE
    INC [G_FLOOR]
    JSR GENERATE_WORLD
    LDAA 1
    STAA [G_MODE]
    CLR [G_MESSAGE]
    JSR SELECT_FLOOR
    JMP COMMIT_TURN
STAIRS_DONE:
    RTS

; Appearance IDs 2..6 and 14..16 map to identification bits 0..7.
MAGIC_INDEX:
    CMPA 14
    BCS MAGIC_OLD_INDEX
    SUBA 9
    TAB
    RTS
MAGIC_OLD_INDEX:
    SUBA 2
    TAB
    RTS
EXTENDED_MAGIC:
    CMPA 5
    BNE MAGIC_MONSTERS
    CLR [G_POISON]
    CLR [G_POISON_TICK]
    LDAA [G_MAX_HP]
    STAA [G_HP]
    RTS
MAGIC_MONSTERS:
    CLR [E_INDEX]
MAGIC_ENEMY_LOOP:
    JSR ENEMY_POINTER
    TST [X + 3]
    BEQ MAGIC_ENEMY_NEXT
    LDAA [ITEM_EFFECT]
    CMPA 7
    BEQ MAGIC_AGGRAVATE
    LDAA [X]
    LDAB [X + 1]
    JSR VISIBLE_CELL
    TST [X]
    BEQ MAGIC_ENEMY_NEXT
    JSR ENEMY_POINTER
    LDAA 6
    STAA [X + 7]
    BRA MAGIC_ENEMY_NEXT
MAGIC_AGGRAVATE:
    LDAA [G_X]
    STAA [X + 4]
    LDAA [G_Y]
    STAA [X + 5]
    CLR [X + 7]
MAGIC_ENEMY_NEXT:
    INC [E_INDEX]
    LDAA [E_INDEX]
    CMPA MAX_ENEMIES
    BNE MAGIC_ENEMY_LOOP
    RTS

; Wand kind encodes charges: 17=3, 18=2, 19=1, 20=empty.
; Ring 21=carried, 22=worn. The equipped ring still occupies one bag slot.
USE_TOOL:
    CMPA 21
    BCC USE_RING
    CMPA 20
    BEQ WAND_EMPTY
    LDAA [G_SLOT]
    INCA
    STAA [G_WAND_SLOT]
    JMP CHOOSE_INSPECT
WAND_EMPTY:
    LDAA 34
    STAA [G_MESSAGE]
    RTS
USE_RING:
    CMPA 22
    BEQ REMOVE_RING
    LDX G_BAG
RING_REMOVE_OLD:
    LDAA [X]
    CMPA 22
    BNE RING_NEXT_SLOT
    DEC [X]
RING_NEXT_SLOT:
    INX
    CPX G_BAG + 6
    BNE RING_REMOVE_OLD
    JSR BAG_ITEM
    INC [X]
    BRA RING_CHANGED
REMOVE_RING:
    DEC [X]
RING_CHANGED:
    LDAA 33
    STAA [G_MESSAGE]
    LDAA 1
    STAA [G_MODE]
    JMP COMMIT_TURN
INSPECT_CONFIRM:
    TST [G_WAND_SLOT]
    BNE FIRE_WAND
    JMP INSPECT_CLOSE
FIRE_WAND:
    LDAA [G_INSPECT_X]
    STAA [NX]
    LDAB [G_INSPECT_Y]
    STAB [NY]
    CMPA [G_X]
    BNE WAND_TARGET
    CMPB [G_Y]
    BNE WAND_TARGET
    JMP INSPECT_CLOSE
WAND_TARGET:
    JSR VISIBLE_CELL
    TST [X]
    BEQ WAND_NO_TARGET
    JSR FIND_ENEMY
    TSTA
    BEQ WAND_NO_TARGET
    LDAB [G_WAND_SLOT]
    DECB
    LDX G_BAG
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    INC [X]
    CLR [G_WAND_SLOT]
    LDAA 1
    STAA [G_MODE]
    LDAA 8
    JMP ATTACK_DAMAGE
WAND_NO_TARGET:
    RTS
