; SPDX-License-Identifier: MIT
; One-shot success/failure phrases; duration zero ends a phrase.
END_FEEDBACK:
    LDAA [G_MODE]
    CMPA 8
    BCS END_SOUND_DONE
    TST [G_CLEAR_SUNG]
    BNE END_SOUND_DONE
    INC [G_CLEAR_SUNG]
    LDX END_NOTES
    CMPA 9
    BEQ PLAY_PHRASE
    LDX FAIL_NOTES
PLAY_PHRASE:
    STX [SOUND_PTR]
END_SOUND_NOTE:
    LDX [SOUND_PTR]
    LDAB [X + 2]
    BEQ END_SOUND_DONE_PLAYING
    STAB [SOUND_DURATION]
    LDAA [X + 1]
    JSR jr_sound_c_start
END_SOUND_DURATION:
    LDX 0x0200
END_SOUND_WAIT:
    DEX
    BNE END_SOUND_WAIT
    DEC [SOUND_DURATION]
    BNE END_SOUND_DURATION
    JSR jr_sound_c_stop
    LDX [SOUND_PTR]
    ADDX8 3
    STX [SOUND_PTR]
    BRA END_SOUND_NOTE
END_SOUND_DONE_PLAYING:
    JSR jr_sound_c_stop
    JSR POLL_KEY
    CLR [G_PENDING]
END_SOUND_DONE:
    RTS
END_NOTES:
    .db 0x06,0xAB,3, 0x05,0x4C,3, 0x04,0x74,4
    .db 0x03,0x57,3, 0x04,0x74,3, 0x03,0x57,10
END_NOTES_END:
    .db 0,0,0
FAIL_NOTES:
    .db 0x06,0xAB,4, 0x08,0x68,4, 0x0A,0x98,12, 0,0,0
START_NOTES:
    .db 0x05,0x4C,3, 0x03,0x57,7, 0,0,0
HIT_NOTES:
    .db 0x0A,0x98,4, 0,0,0
; Preserve caller state and the JR-200 video/input resources changed by the game.
ENTRY:
    TPA
    STAA [SAVE_CC]
    SEI
    STS [SAVE_SP]
    LDS STACK_TOP
    LDX JR200_PCG_BANK1
    STX [TEXT_SRC]
    LDX SAVE_PCG
    STX [TEXT_DEST]
    CLRB
    JSR COPY_BYTES
    LDX JR200_SCREEN_CODES
    STX [TEXT_SRC]
    LDX SAVE_SCREEN_CODES
    STX [TEXT_DEST]
    CLRB
    JSR COPY_BYTES
    LDX JR200_SCREEN_CODES + 0x100
    STX [TEXT_SRC]
    LDX SAVE_SCREEN_CODES + 0x100
    STX [TEXT_DEST]
    CLRB
    JSR COPY_BYTES
    LDX JR200_SCREEN_CODES + 0x200
    STX [TEXT_SRC]
    LDX SAVE_SCREEN_CODES + 0x200
    STX [TEXT_DEST]
    CLRB
    JSR COPY_BYTES
    LDX JR200_SCREEN_ATTRIBUTES
    STX [TEXT_SRC]
    LDX SAVE_ATTRIBUTES
    STX [TEXT_DEST]
    CLRB
    JSR COPY_BYTES
    LDX JR200_SCREEN_ATTRIBUTES + 0x100
    STX [TEXT_SRC]
    LDX SAVE_ATTRIBUTES + 0x100
    STX [TEXT_DEST]
    CLRB
    JSR COPY_BYTES
    LDX JR200_SCREEN_ATTRIBUTES + 0x200
    STX [TEXT_SRC]
    LDX SAVE_ATTRIBUTES + 0x200
    STX [TEXT_DEST]
    CLRB
    JSR COPY_BYTES
    LDX STATE_BEGIN
    CLRA
ENTRY_ZERO:
    STAA [X]
    INX
    CPX STATE_END
    BNE ENTRY_ZERO
    LDX SCRATCH_BEGIN
ENTRY_SCRATCH_ZERO:
    STAA [X]
    INX
    CPX SCRATCH_END
    BNE ENTRY_SCRATCH_ZERO
    LDX FAST_BEGIN
ENTRY_FAST_ZERO:
    STAA [X]
    INX
    CPX FAST_END
    BNE ENTRY_FAST_ZERO
    LDAA [JR200_KEY_IRQ_MASK]
    STAA [SAVE_KEY_MASK]
    ORAA 1
    STAA [JR200_KEY_IRQ_MASK]
    LDAA [JR200_KEY_IRQ_STATUS]
    LDAA [JR200_BORDER]
    STAA [SAVE_BORDER]
    CLRA
    STAA [JR200_BORDER]
    LDAA 1
    STAA [G_SEED + 1]
    STAA [G_DIFFICULTY]
    JMP REDRAW

COPY_BYTES:
    LDX [TEXT_SRC]
    LDAA [X]
    INX
    STX [TEXT_SRC]
    LDX [TEXT_DEST]
    STAA [X]
    INX
    STX [TEXT_DEST]
    DECB
    BNE COPY_BYTES
    RTS

EXIT_GAME:
    SEI
    JSR jr_sound_all_stop
    LDX SAVE_SCREEN_CODES
    STX [TEXT_SRC]
    LDX JR200_SCREEN_CODES
    STX [TEXT_DEST]
    CLRB
    JSR COPY_BYTES
    LDX SAVE_SCREEN_CODES + 0x100
    STX [TEXT_SRC]
    LDX JR200_SCREEN_CODES + 0x100
    STX [TEXT_DEST]
    CLRB
    JSR COPY_BYTES
    LDX SAVE_SCREEN_CODES + 0x200
    STX [TEXT_SRC]
    LDX JR200_SCREEN_CODES + 0x200
    STX [TEXT_DEST]
    CLRB
    JSR COPY_BYTES
    LDX SAVE_PCG
    STX [TEXT_SRC]
    LDX JR200_PCG_BANK1
    STX [TEXT_DEST]
    CLRB
    JSR COPY_BYTES
    LDX SAVE_ATTRIBUTES
    STX [TEXT_SRC]
    LDX JR200_SCREEN_ATTRIBUTES
    STX [TEXT_DEST]
    CLRB
    JSR COPY_BYTES
    LDX SAVE_ATTRIBUTES + 0x100
    STX [TEXT_SRC]
    LDX JR200_SCREEN_ATTRIBUTES + 0x100
    STX [TEXT_DEST]
    CLRB
    JSR COPY_BYTES
    LDX SAVE_ATTRIBUTES + 0x200
    STX [TEXT_SRC]
    LDX JR200_SCREEN_ATTRIBUTES + 0x200
    STX [TEXT_DEST]
    CLRB
    JSR COPY_BYTES
    LDAA [SAVE_KEY_MASK]
    STAA [JR200_KEY_IRQ_MASK]
    LDAA [SAVE_BORDER]
    STAA [JR200_BORDER]
    LDS [SAVE_SP]
    LDAA [SAVE_CC]
    TAP
EXIT_RESTORE_READY:
    RTS

; Set the 16-bit Z flag from A:B, keeping N,V,C,H from the high operation.
WORD_Z:
    PSHA
    TPA
    STAA [WORD_CC]
    PULA
    TSTA
    BNE WORD_NOT_ZERO
    TSTB
    BNE WORD_NOT_ZERO
    PSHA
    LDAA [WORD_CC]
    ORAA 4
    TAP
    PULA
    RTS
WORD_NOT_ZERO:
    PSHA
    LDAA [WORD_CC]
    ANDA 0xFB
    TAP
    PULA
    RTS

; Unsigned 8x8 -> A:B. X is preserved. No HD6301 instructions.
MULTIPLY:
    STAA [MUL_LEFT + 1]
    CLR [MUL_LEFT]
    STAB [MUL_RIGHT]
    CLR [MUL_RESULT]
    CLR [MUL_RESULT + 1]
    LDAA 8
    STAA [MUL_COUNT]
MULTIPLY_BIT:
    LSR [MUL_RIGHT]
    BCC MULTIPLY_SHIFT
    LDAB [MUL_RESULT + 1]
    LDAA [MUL_RESULT]
    ADDB [MUL_LEFT + 1]
    ADCA [MUL_LEFT]
    STAB [MUL_RESULT + 1]
    STAA [MUL_RESULT]
MULTIPLY_SHIFT:
    ASL [MUL_LEFT + 1]
    ROL [MUL_LEFT]
    DEC [MUL_COUNT]
    BNE MULTIPLY_BIT
    LDAB [MUL_RESULT + 1]
    LDAA [MUL_RESULT]
    RTS

POLL_KEY:
    ; Key-On status distinguishes repeated presses even when the data latch keeps
    ; its previous value after release. Reading the status acknowledges the event.
    STX [POLL_SAVE_X]
    LDAA [JR200_KEY_IRQ_STATUS]
    BITA 1
    BEQ POLL_DONE
    LDAA [JR200_KEY_DATA]
    CMPA 0x1B
    BEQ POLL_EXIT
    CMPA 0x03
    BEQ POLL_EXIT
    CMPA 0x0D
    BEQ POLL_CONFIRM
    CMPA 0x20
    BEQ POLL_BACK
    ORAA 0x20
    LDAB 1
    CMPA 0x77
    BEQ POLL_SAMPLE
    INCB
    CMPA 0x78
    BEQ POLL_SAMPLE
    INCB
    CMPA 0x61
    BEQ POLL_SAMPLE
    INCB
    CMPA 0x64
    BEQ POLL_SAMPLE
    LDAB 7
    CMPA 0x71
    BEQ POLL_SAMPLE
    INCB
    CMPA 0x65
    BEQ POLL_SAMPLE
    INCB
    CMPA 0x7A
    BEQ POLL_SAMPLE
    INCB
    CMPA 0x63
    BEQ POLL_SAMPLE
    INCB
    CMPA 0x73
    BEQ POLL_SAMPLE
    BRA POLL_DONE
POLL_EXIT:
    JMP EXIT_GAME
POLL_CONFIRM:
    LDAB 5
    BRA POLL_SAMPLE
POLL_BACK:
    LDAB 6
POLL_SAMPLE:
    STAB [G_PREVIOUS]
    ; First pending edge wins until dispatch consumes it.
    TST [G_PENDING]
    BNE POLL_DONE
    STAB [G_PENDING]
POLL_DONE:
    LDX [POLL_SAVE_X]
    RTS
; Clear only text rows when the map renderer will overwrite all terrain cells.

CLEAR:
    LDAA [G_MODE]
    CMPA 1
    BEQ CLEAR_WORLD
    CMPA 5
    BEQ CLEAR_WORLD
    LDX FRAMEBUFFER
    LDAA JR200_CHAR_SPACE
CLEAR_NEXT:
    STAA [X]
    INX
    CPX FRAMEBUFFER + 768
    BNE CLEAR_NEXT
    RTS
CLEAR_WORLD:
    LDX FRAMEBUFFER
    LDAA JR200_CHAR_SPACE
    LDAB 64
    JSR CLEAR_TEXT_ROWS
    LDX FRAMEBUFFER + 704
    LDAB 64
CLEAR_TEXT_ROWS:
    STAA [X]
    INX
    DECB
    BNE CLEAR_TEXT_ROWS
    RTS
; A ASCII -> JR-200 display code. Preserve B and X.
GLYPH:
GLYPH_STORE:
    STAA [X]
    RTS
; X string, A:B VRAM address.
TEXT:
    PSHB
    CLR [TEXT_PAIR_INDEX]
    STX [TEXT_SRC]
    STAA [TEXT_DEST]
    STAB [TEXT_DEST + 1]
TEXT_NEXT:
    LDX [TEXT_SRC]
    LDAA [X]
    BEQ TEXT_DONE
    INX
    STX [TEXT_SRC]
    JSR TEXT_EMIT
    BRA TEXT_NEXT
TEXT_DONE:
    PULB
    RTS
; Tokens 128..255 expand to two earlier symbols; literals are ASCII.
TEXT_EMIT:
    TSTA
    BPL TEXT_LITERAL
    ASLA
    STAA [TEXT_PAIR_INDEX + 1]
    LDX TEXT_PAIRS
    ADDX16 TEXT_PAIR_INDEX
    LDAB [X + 1]
    PSHB
    LDAA [X]
    JSR TEXT_EMIT
    PULA
    BRA TEXT_EMIT
TEXT_LITERAL:
    LDX [TEXT_DEST]
    CPX FRAMEBUFFER + 768
    BGE TEXT_EMIT_DONE
    JSR GLYPH
    INX
    STX [TEXT_DEST]
TEXT_EMIT_DONE:
    RTS

; Compose offscreen, then commit each cell as one short transition. A wall that
; appears gets its attribute first; a wall that disappears gets its character
; replaced first. Therefore a visible wall never carries a floor attribute.
PRESENT:
    JMP COLORIZE

; Apply a black-background JR-200 palette without changing game state or glyphs.
COLORIZE:
    LDX FRAMEBUFFER
    STX [COLOR_CODE_PTR]
    LDX JR200_SCREEN_CODES
    STX [COLOR_SCREEN_PTR]
    LDX JR200_SCREEN_ATTRIBUTES
    STX [COLOR_ATTR_PTR]
    CLR [COLOR_ROW]
    CLR [COLOR_COL]
COLOR_NEXT:
    LDX [COLOR_CODE_PTR]
    LDAA [X]
    STAA [COLOR_CODE]
    CMPA 0x80
    BCS COLOR_STANDARD
    TST [G_MODE]
    BEQ COLOR_TITLE
    SUBA 0x80
    BEQ COLOR_USER_BLUE
    CMPA 1
    BEQ COLOR_USER_CYAN
    CMPA 2
    BEQ COLOR_USER_BLUE
    CMPA 5
    BCS COLOR_USER_CYAN
    BEQ COLOR_USER_YELLOW
    CMPA 6
    BEQ COLOR_USER_GREEN
    CMPA 7
    BEQ COLOR_USER_YELLOW
    CMPA 8
    BEQ COLOR_USER_MAGENTA
    CMPA 9
    BEQ COLOR_USER_CYAN
    CMPA 10
    BEQ COLOR_USER_WHITE
    CMPA 11
    BEQ COLOR_USER_BLUE
    CMPA 12
    BEQ COLOR_USER_YELLOW
    CMPA 29
    BCS COLOR_USER_RED
COLOR_USER_MAGENTA:
    LDAA ATTR_USER_MAGENTA
    BRA COLOR_STORE
COLOR_USER_RED:
    LDAA ATTR_USER_RED
    BRA COLOR_STORE
COLOR_USER_GREEN:
    LDAA ATTR_USER_GREEN
    BRA COLOR_STORE
COLOR_USER_CYAN:
    LDAA ATTR_USER_CYAN
    BRA COLOR_STORE
COLOR_USER_YELLOW:
    LDAA ATTR_USER_YELLOW
    BRA COLOR_STORE
COLOR_USER_WHITE:
    LDAA ATTR_USER_WHITE
    BRA COLOR_STORE
COLOR_USER_BLUE:
    LDAA ATTR_USER_BLUE
    BRA COLOR_STORE
COLOR_TITLE:
    LDAA [COLOR_CODE]
    BITA 1
    BEQ COLOR_USER_CYAN
    BRA COLOR_USER_YELLOW
COLOR_STANDARD:
    CMPA 0x3E
    BEQ COLOR_STANDARD_YELLOW
    TST [COLOR_ROW]
    BEQ COLOR_STANDARD_CYAN
    LDAA [COLOR_ROW]
    CMPA 22
    BCC COLOR_STANDARD_YELLOW
    LDAA ATTR_STANDARD_WHITE
    BRA COLOR_STORE
COLOR_STANDARD_CYAN:
    LDAA ATTR_STANDARD_CYAN
    BRA COLOR_STORE
COLOR_STANDARD_YELLOW:
    LDAA ATTR_STANDARD_YELLOW
COLOR_STORE:
    STAA [COLOR_ATTRIBUTE]
    LDX [COLOR_SCREEN_PTR]
    LDAA [X]
    CMPA WALL_SCREEN_CODE
    BNE COLOR_ATTRIBUTE_FIRST
    LDAA [COLOR_CODE]
    CMPA WALL_SCREEN_CODE
    BEQ COLOR_ATTRIBUTE_FIRST
    ; Remove the old wall before replacing its wall color with the new color.
    STAA [X]
    BRA COLOR_ATTRIBUTE_WRITE
COLOR_ATTRIBUTE_FIRST:
    ; Install the new color before making a new wall character visible.
    LDX [COLOR_ATTR_PTR]
    LDAA [COLOR_ATTRIBUTE]
    CMPA [X]
    BEQ COLOR_CODE_WRITE
    STAA [X]
COLOR_CODE_WRITE:
    LDX [COLOR_SCREEN_PTR]
    LDAA [COLOR_CODE]
    CMPA [X]
    BEQ COLOR_CELL_READY
    STAA [X]
    BRA COLOR_CELL_READY
COLOR_ATTRIBUTE_WRITE:
    LDX [COLOR_ATTR_PTR]
    LDAA [COLOR_ATTRIBUTE]
    CMPA [X]
    BEQ COLOR_CELL_READY
    STAA [X]
COLOR_CELL_READY:
    LDX [COLOR_ATTR_PTR]
    INX
    STX [COLOR_ATTR_PTR]
    LDX [COLOR_SCREEN_PTR]
    INX
    STX [COLOR_SCREEN_PTR]
    LDX [COLOR_CODE_PTR]
    INX
    STX [COLOR_CODE_PTR]
    INC [COLOR_COL]
    LDAA [COLOR_COL]
    CMPA JR200_SCREEN_WIDTH
    BNE COLOR_CHECK_DONE
    CLR [COLOR_COL]
    INC [COLOR_ROW]
COLOR_CHECK_DONE:
    LDX [COLOR_ATTR_PTR]
    CPX JR200_SCREEN_ATTRIBUTES_END
    BEQ COLOR_DONE
    JMP COLOR_NEXT
COLOR_DONE:
    RTS

; Hit -> splinters -> dust at the contacted map cell. Only that VRAM byte changes.
STRIKE_SCENE:
    JSR TILE_DESTINATION
    LDAA [DRAW]
    ADDA ((JR200_SCREEN_CODES - FRAMEBUFFER) >> 8)
    STAA [DRAW]
    LDX [DRAW]
    LDAA [X]
    PSHA
    LDAA [DRAW]
    ADDA ((JR200_SCREEN_ATTRIBUTES - JR200_SCREEN_CODES) >> 8)
    STAA [COLOR_ATTR_PTR]
    LDAA [DRAW + 1]
    STAA [COLOR_ATTR_PTR + 1]
    LDX [COLOR_ATTR_PTR]
    LDAA [X]
    STAA [STRIKE_ATTR]
    LDAA ATTR_STANDARD_YELLOW
    STAA [X]
    CLR [STRIKE_PHASE]
STRIKE_FRAME:
    LDX STRIKE_GLYPHS
    LDAB [STRIKE_PHASE]
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    LDX [DRAW]
    STAA [X]
    LDX STRIKE_NOTE
    JSR PLAY_PHRASE
    INC [STRIKE_PHASE]
    LDAA [STRIKE_PHASE]
    CMPA 3
    BCS STRIKE_FRAME
    LDX [DRAW]
    PULA
    STAA [X]
    LDX [COLOR_ATTR_PTR]
    LDAA [STRIKE_ATTR]
    STAA [X]
    RTS
STRIKE_GLYPHS:
    .db 0x2A,0x2B,0x2E
STRIKE_NOTE:
    .db 0x06,0xAB,1, 0,0,0
