; SPDX-License-Identifier: MIT
; Unequal recursive partitions and randomized connected corridors.
TERRAIN_LAYOUT:
    LDAA 1
    STAA [GEN_N]
    STAA [RECT_X]
    STAA [RECT_Y]
    LDAA MAP_WIDTH - 2
    STAA [RECT_W]
    LDAA MAP_HEIGHT - 2
    STAA [RECT_H]
TERRAIN_TARGET:
    JSR RANDOM
    ANDA 3
    CMPA 3
    BEQ TERRAIN_TARGET
    ADDA 6
    STAA [GEN_TARGET]
TERRAIN_PARTITION:
    CLR [GEN_BIG]
    CLR [ROOM]
    CLRB
TERRAIN_FIND_SPLIT:
    LDX RECT_W
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    CMPA [GEN_BIG]
    BLS TERRAIN_FIND_HEIGHT
    STAA [GEN_BIG]
    STAB [ROOM]
    CLR [GEN_AXIS]
TERRAIN_FIND_HEIGHT:
    LDX RECT_H
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    CMPA [GEN_BIG]
    BLS TERRAIN_FIND_NEXT
    STAA [GEN_BIG]
    STAB [ROOM]
    LDAA 1
    STAA [GEN_AXIS]
TERRAIN_FIND_NEXT:
    INCB
    CMPB [GEN_N]
    BNE TERRAIN_FIND_SPLIT
    LDAA [GEN_BIG]
    CMPA 11
    BCS TERRAIN_PARTITIONS_DONE
TERRAIN_CUT:
    JSR RANDOM
    ANDA 31
    ADDA 5
    STAA [GEN_CUT]
    ADDA 6
    CMPA [GEN_BIG]
    BHI TERRAIN_CUT
    JSR TERRAIN_LOAD_RECT
    TST [GEN_AXIS]
    BNE TERRAIN_SPLIT_HEIGHT
    LDAA [GEN_CUT]
    STAA [ROOM_W]
    LDAB [ROOM]
    JSR TERRAIN_STORE_RECT
    LDAA [ROOM_X]
    ADDA [GEN_CUT]
    INCA
    STAA [ROOM_X]
    LDAA [GEN_BIG]
    SUBA [GEN_CUT]
    DECA
    STAA [ROOM_W]
    BRA TERRAIN_SPLIT_STORE
TERRAIN_SPLIT_HEIGHT:
    LDAA [GEN_CUT]
    STAA [ROOM_H]
    LDAB [ROOM]
    JSR TERRAIN_STORE_RECT
    LDAA [ROOM_Y]
    ADDA [GEN_CUT]
    INCA
    STAA [ROOM_Y]
    LDAA [GEN_BIG]
    SUBA [GEN_CUT]
    DECA
    STAA [ROOM_H]
TERRAIN_SPLIT_STORE:
    LDAB [GEN_N]
    JSR TERRAIN_STORE_RECT
    INC [GEN_N]
    LDAA [GEN_N]
    CMPA [GEN_TARGET]
    BEQ TERRAIN_PARTITIONS_DONE
    JMP TERRAIN_PARTITION
TERRAIN_PARTITIONS_DONE:
    CLR [GEN_OMITTED]
    LDAA [GEN_N]
    STAA [GEN_ROOMS]
    SUBA 6
    STAA [GEN_CUT]
    BEQ TERRAIN_ROOMS_BEGIN
TERRAIN_OMIT:
    JSR RANDOM
    ANDA 1
    BEQ TERRAIN_OMIT_NEXT
TERRAIN_OMIT_ROLL:
    JSR TERRAIN_ROOM_ROLL
    LDX TERRAIN_BITS
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    BITA [GEN_OMITTED]
    BNE TERRAIN_OMIT_ROLL
    ORAA [GEN_OMITTED]
    STAA [GEN_OMITTED]
    DEC [GEN_ROOMS]
TERRAIN_OMIT_NEXT:
    DEC [GEN_CUT]
    BNE TERRAIN_OMIT
TERRAIN_ROOMS_BEGIN:
    CLR [ROOM]
TERRAIN_ROOM:
    JSR TERRAIN_LOAD_RECT
    LDAA [ROOM_W]
    STAA [GEN_BIG]
TERRAIN_WIDTH:
    JSR RANDOM
    ANDA 31
    ADDA 4
    CMPA [GEN_BIG]
    BHI TERRAIN_WIDTH
    STAA [ROOM_W]
TERRAIN_X_ROLL:
    JSR RANDOM
    ANDA 31
    STAA [GEN_CUT]
    ADDA [ROOM_W]
    CMPA [GEN_BIG]
    BHI TERRAIN_X_ROLL
    LDAA [ROOM_X]
    ADDA [GEN_CUT]
    STAA [ROOM_X]
    LDAA [ROOM_H]
    STAA [GEN_BIG]
TERRAIN_HEIGHT:
    JSR RANDOM
    ANDA 15
    ADDA 4
    CMPA [GEN_BIG]
    BHI TERRAIN_HEIGHT
    STAA [ROOM_H]
TERRAIN_Y_ROLL:
    JSR RANDOM
    ANDA 15
    STAA [GEN_CUT]
    ADDA [ROOM_H]
    CMPA [GEN_BIG]
    BHI TERRAIN_Y_ROLL
    LDAA [ROOM_Y]
    ADDA [GEN_CUT]
    STAA [ROOM_Y]
    LDAB [ROOM]
    JSR TERRAIN_STORE_RECT
    LDX ROOM_CX
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [ROOM_W]
    LSRA
    ADDA [ROOM_X]
    STAA [X]
    LDX ROOM_CY
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [ROOM_H]
    LSRA
    ADDA [ROOM_Y]
    STAA [X]
    LDX GEN_LINKS
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    CLR [X]
    LDX TERRAIN_BITS
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    BITA [GEN_OMITTED]
    BNE TERRAIN_ROOM_NEXT
    LDAA [ROOM_Y]
    STAA [GY]
TERRAIN_ROW:
    JSR POLL_KEY
    LDAA [ROOM_X]
    STAA [GX]
TERRAIN_COLUMN:
    JSR TERRAIN_DOT
    INC [GX]
    LDAA [GX]
    SUBA [ROOM_X]
    CMPA [ROOM_W]
    BNE TERRAIN_COLUMN
    INC [GY]
    LDAA [GY]
    SUBA [ROOM_Y]
    CMPA [ROOM_H]
    BNE TERRAIN_ROW
TERRAIN_ROOM_NEXT:
    INC [ROOM]
    LDAA [ROOM]
    CMPA [GEN_N]
    BNE TERRAIN_ROOM_CONTINUE
    JMP TERRAIN_TREE_BEGIN
TERRAIN_ROOM_CONTINUE:
    JMP TERRAIN_ROOM
TERRAIN_LOAD_RECT:
    LDAB [ROOM]
    LDX RECT_X
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    STAA [ROOM_X]
    LDX RECT_Y
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    STAA [ROOM_Y]
    LDX RECT_W
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    STAA [ROOM_W]
    LDX RECT_H
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    STAA [ROOM_H]
    RTS
TERRAIN_STORE_RECT:
    LDX RECT_X
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [ROOM_X]
    STAA [X]
    LDX RECT_Y
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [ROOM_Y]
    STAA [X]
    LDX RECT_W
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [ROOM_W]
    STAA [X]
    LDX RECT_H
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [ROOM_H]
    STAA [X]
    RTS
TERRAIN_TREE_BEGIN:
    JSR TERRAIN_ROOM_ROLL
    LDX TERRAIN_BITS
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    STAA [GEN_VISITED]
    LDAB [GEN_N]
    LDX TERRAIN_FULL_MASKS
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    STAA [GEN_FULL]
TERRAIN_TREE:
    JSR TERRAIN_EDGE
    LDAA [GEN_VISITED]
    ANDA [GEN_MASK]
    BEQ TERRAIN_TREE
    CMPA [GEN_MASK]
    BEQ TERRAIN_TREE
    LDAA [GEN_VISITED]
    ORAA [GEN_MASK]
    STAA [GEN_VISITED]
    JSR TERRAIN_CONNECT
    LDAA [GEN_VISITED]
    CMPA [GEN_FULL]
    BNE TERRAIN_TREE
    JSR RANDOM
    ANDA 1
    BEQ TERRAIN_START
TERRAIN_EXTRA:
    JSR TERRAIN_EDGE
    LDAB [GEN_A]
    LDX GEN_LINKS
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    BITA [GEN_EDGE_BIT]
    BNE TERRAIN_EXTRA
    JSR TERRAIN_CONNECT
TERRAIN_START:
    JSR TERRAIN_ROOM_ROLL
    LDX TERRAIN_BITS
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    BITA [GEN_OMITTED]
    BNE TERRAIN_START
    STAB [GEN_START]
    LDX ROOM_CX
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    STAA [G_X]
    LDX ROOM_CY
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    STAA [G_Y]
    CLR [GEN_DISTANCE]
    CLR [ROOM]
TERRAIN_GOAL:
    LDAB [ROOM]
    CMPB [GEN_START]
    BNE FAR_TERRAIN_0_0
    JMP TERRAIN_GOAL_NEXT
FAR_TERRAIN_0_0:
    LDX TERRAIN_BITS
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    BITA [GEN_OMITTED]
    BEQ FAR_TERRAIN_1_0
    JMP TERRAIN_GOAL_NEXT
FAR_TERRAIN_1_0:
    LDX RECT_X
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    STAA [GX]
    LDX ROOM_CX
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    CMPA [G_X]
    BCS TERRAIN_GOAL_LEFT
    LDX RECT_W
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    ADDA [GX]
    DECA
    STAA [GX]
TERRAIN_GOAL_LEFT:
    LDX RECT_Y
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    STAA [GY]
    LDX ROOM_CY
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    CMPA [G_Y]
    BCS TERRAIN_GOAL_TOP
    LDX RECT_H
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    ADDA [GY]
    DECA
    STAA [GY]
TERRAIN_GOAL_TOP:
    LDAA [GX]
    SUBA [G_X]
    BPL TERRAIN_GOAL_X
    NEGA
TERRAIN_GOAL_X:
    STAA [TEMP]
    LDAA [GY]
    SUBA [G_Y]
    BPL TERRAIN_GOAL_Y
    NEGA
TERRAIN_GOAL_Y:
    ADDA [TEMP]
    CMPA [GEN_DISTANCE]
    BLS TERRAIN_GOAL_NEXT
    STAA [GEN_DISTANCE]
    LDAA [GY]
    STAA [ROOM_Y]
    LDAA [GX]
    STAA [ROOM_X]
TERRAIN_GOAL_NEXT:
    INC [ROOM]
    LDAA [ROOM]
    CMPA [GEN_N]
    BEQ TERRAIN_GOAL_DONE
    JMP TERRAIN_GOAL
TERRAIN_GOAL_DONE:
    LDAA [ROOM_X]
    LDAB [ROOM_Y]
    JSR CELL
    LDAA 3
    LDAB [GEN_FLOOR]
    INCB
    CMPB [G_DEPTH]
    BNE TERRAIN_GOAL_STORE
    INCA
TERRAIN_GOAL_STORE:
    JSR WRITE_CELL
    RTS
TERRAIN_ROOM_ROLL:
    JSR RANDOM
    ANDA 7
    CMPA [GEN_N]
    BCC TERRAIN_ROOM_ROLL
    TAB
    RTS
TERRAIN_EDGE:
    JSR POLL_KEY
    JSR TERRAIN_ROOM_ROLL
    STAB [GEN_A]
TERRAIN_EDGE_OTHER:
    JSR TERRAIN_ROOM_ROLL
    CMPB [GEN_A]
    BEQ TERRAIN_EDGE_OTHER
    STAB [GEN_B]
    LDX TERRAIN_BITS
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    STAA [GEN_EDGE_BIT]
    STAA [GEN_MASK]
    LDAB [GEN_A]
    LDX TERRAIN_BITS
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    ORAA [GEN_MASK]
    STAA [GEN_MASK]
    RTS
TERRAIN_CONNECT:
    LDAB [GEN_A]
    LDX GEN_LINKS
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    ORAA [GEN_EDGE_BIT]
    STAA [X]
    LDX TERRAIN_BITS
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    STAA [GEN_MASK]
    LDAB [GEN_B]
    LDX GEN_LINKS
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    ORAA [GEN_MASK]
    STAA [X]
    LDAB [GEN_A]
    LDX ROOM_CX
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    STAA [GX]
    LDX ROOM_CY
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    STAA [GY]
    LDAB [GEN_B]
    LDX ROOM_CX
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    STAA [NX]
    LDX ROOM_CY
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    STAA [NY]
    JSR RANDOM
    ANDA 1
    BEQ TERRAIN_HORIZONTAL_FIRST
    JSR TERRAIN_VERTICAL
    JMP TERRAIN_HORIZONTAL
TERRAIN_HORIZONTAL_FIRST:
    JSR TERRAIN_HORIZONTAL
    JMP TERRAIN_VERTICAL
TERRAIN_HORIZONTAL:
    JSR TERRAIN_DOT
    LDAA [GX]
    CMPA [NX]
    BEQ TERRAIN_AXIS_DONE
    BHI TERRAIN_LEFT
    INC [GX]
    BRA TERRAIN_HORIZONTAL
TERRAIN_LEFT:
    DEC [GX]
    BRA TERRAIN_HORIZONTAL
TERRAIN_VERTICAL:
    JSR TERRAIN_DOT
    LDAA [GY]
    CMPA [NY]
    BEQ TERRAIN_AXIS_DONE
    BHI TERRAIN_UP
    INC [GY]
    BRA TERRAIN_VERTICAL
TERRAIN_UP:
    DEC [GY]
    BRA TERRAIN_VERTICAL
TERRAIN_AXIS_DONE:
    RTS
TERRAIN_DOT:
    LDAA [GX]
    LDAB [GY]
    JSR CELL
    LDAA 1
    JSR WRITE_CELL
    RTS
TERRAIN_BITS: .db 1,2,4,8,16,32,64,128
TERRAIN_FULL_MASKS: .db 0,1,3,7,15,31,63,127,255
