; SPDX-License-Identifier: MIT
; Eight-way player actions, twelve enemy types, and survival rules.
WORLD_DIRECTION:
    CLR [ACTION]
    CLR [G_MESSAGE]
    LDAB [G_KEY]
    STAB [LAST_DIRECTION]
    DECB
    LDX DIRECTION_DX
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [G_X]
    ADDA [X]
    STAA [NX]
    LDX DIRECTION_DY
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [G_Y]
    ADDA [X]
    STAA [NY]
    CMPB 6
    BCS DIRECTION_READY
    LDAA [NX]
    PSHA
    LDAA [G_X]
    STAA [NX]
    JSR WALKABLE
    TAB
    PULA
    STAA [NX]
    TSTB
    BEQ DIRECTION_BLOCKED
    LDAA [NY]
    PSHA
    LDAA [G_Y]
    STAA [NY]
    JSR WALKABLE
    TAB
    PULA
    STAA [NY]
    TSTB
    BEQ DIRECTION_BLOCKED
DIRECTION_READY:
    JSR WALKABLE
    TSTA
    BNE DIRECTION_OPEN
DIRECTION_BLOCKED:
    RTS
DIRECTION_OPEN:
    JSR FIND_ENEMY
    TSTA
    BNE DIRECTION_ENEMY
    JMP PLAYER_MOVE
DIRECTION_ENEMY:
    STAA [CANDIDATE]
    LDAA [G_ATTACK]
    TST [G_BUFF]
    BEQ ATTACK_UNBUFFED
    INCA
ATTACK_UNBUFFED:
    LDAB [CANDIDATE]
    DECB
    LDX ENEMY_DEFENSE
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    SUBA [X]
ATTACK_DAMAGE:
    TSTA
    BNE ATTACK_POSITIVE
    INCA
ATTACK_POSITIVE:
    STAA [DAMAGE]
    JSR STRIKE_SCENE
    LDX [E_PTR]
    LDAA [X + 3]
    SUBA [DAMAGE]
    BHI ENEMY_WOUNDED
    CLR [X + 3]
    INC [G_KILLS]
    LDAA 3
    STAA [G_MESSAGE]
    LDAA [G_LEVEL]
    CMPA 32
    BCC ATTACK_COMMITTED
    LDAA [G_KILLS]
    CMPA 3
    BCS ATTACK_COMMITTED
    CLR [G_KILLS]
    INC [G_LEVEL]
    LDAA [G_MAX_HP]
    ADDA 2
    STAA [G_MAX_HP]
    LDAA [G_HP]
    ADDA 2
    STAA [G_HP]
    LDAA 4
    STAA [G_MESSAGE]
    BRA ATTACK_COMMITTED
ENEMY_WOUNDED:
    STAA [X + 3]
    LDAA 2
    STAA [G_MESSAGE]
ATTACK_COMMITTED:
    JMP COMMIT_TURN
PLAYER_MOVE:
    LDAA [NX]
    STAA [G_X]
    LDAA [NY]
    STAA [G_Y]
    JSR TRIGGER_TRAP
    JSR PICKUP
    LDAA [G_MODE]
    CMPA 9
    BEQ PLAYER_WON
    LDAA [G_KEY]
    CMPA 4
    BHI PLAYER_WON
    LDAA 1
    STAA [G_AUTOWALK]
PLAYER_WON:
    JMP COMMIT_TURN
WALKABLE:
    LDAA [NX]
    CMPA MAP_WIDTH
    BCC NOT_WALKABLE
    LDAB [NY]
    CMPB MAP_HEIGHT
    BCC NOT_WALKABLE
    JSR CELL
    ANDA 127
    CMPA 5
    BEQ NOT_WALKABLE
    TSTA
    RTS
NOT_WALKABLE:
    CLRA
    RTS
COMMIT_TURN:
    LDAB [G_TURNS + 1]
    LDAA [G_TURNS]
    ADDB ((1) & 255)
    ADCA ((1) >> 8)
    STAB [G_TURNS + 1]
    STAA [G_TURNS]
    LDAA [G_MODE]
    CMPA 9
    BNE TURN_CONTINUES
    CLR [G_AUTOWALK]
    RTS
TURN_CONTINUES:
    TST [G_HP]
    BNE TURN_PLAYER_ALIVE
    JMP TURN_DIE
TURN_PLAYER_ALIVE:
    TST [G_BUFF]
    BEQ TURN_FOOD
    DEC [G_BUFF]
TURN_FOOD:
    TST [G_POISON]
    BEQ POISON_TICK_DONE
    DEC [G_POISON]
    INC [G_POISON_TICK]
    LDAA [G_POISON_TICK]
    ANDA 1
    BNE POISON_TICK_DONE
    TST [G_HP]
    BEQ POISON_TICK_DONE
    DEC [G_HP]
    LDAA 16
    STAA [G_MESSAGE]
POISON_TICK_DONE:
    TST [G_HP]
    BNE POISON_SURVIVED
    JMP TURN_DIE
POISON_SURVIVED:
    TST [G_FOOD]
    BEQ STARVING
    LDAA [G_TURNS + 1]
    ANDA 1
    BEQ FOOD_CONSUME
    LDX G_BAG
FOOD_RING_SCAN:
    LDAA [X]
    CMPA 22
    BEQ FOOD_SKIP
    INX
    CPX G_BAG + 6
    BNE FOOD_RING_SCAN
FOOD_CONSUME:
    DEC [G_FOOD]
FOOD_SKIP:
    CLR [G_STARVE]
    INC [G_REGEN]
    LDAA [G_REGEN]
    CMPA 12
    BCS TURN_ENEMIES
    CLR [G_REGEN]
    LDAA [G_HP]
    CMPA [G_MAX_HP]
    BCC TURN_ENEMIES
    INC [G_HP]
    BRA TURN_ENEMIES
STARVING:
    CLR [G_REGEN]
    INC [G_STARVE]
    LDAA [G_STARVE]
    ANDA 1
    BNE TURN_ENEMIES
    TST [G_HP]
    BEQ TURN_ENEMIES
    DEC [G_HP]
TURN_ENEMIES:
    LDAA [G_MODE]
    CMPA 9
    BNE TURN_NOT_WON
    CLR [G_AUTOWALK]
    RTS
TURN_NOT_WON:
    JSR ENSURE_VISIBILITY
    TST [NEW_SIGHT]
    BEQ NO_NEW_SIGHT
    CLR [G_AUTOWALK]
NO_NEW_SIGHT:
    JSR ENEMIES_TURN
    TST [G_HP]
    BNE TURN_ALIVE
TURN_DIE:
    CLR [G_SUSPEND]
    CLR [G_AUTOWALK]
    LDAA 8
    STAA [G_MODE]
TURN_ALIVE:
    LDAA [G_FOOD]
    CMPA 40
    BHI TURN_DONE
    CLR [G_AUTOWALK]
    TST [G_MESSAGE]
    BNE TURN_DONE
    LDAA 5
    STAA [G_MESSAGE]
TURN_DONE:
    RTS
ENEMIES_TURN:
    JSR POLL_KEY
    CLR [E_INDEX]
ENEMY_TURN_LOOP:
    TST [G_HP]
    BNE ENEMY_PLAYER_ALIVE
    RTS
ENEMY_PLAYER_ALIVE:
    JSR ENEMY_POINTER
    TST [X + 3]
    BNE ENEMY_ACTIVE
    JMP ENEMY_TURN_NEXT
ENEMY_ACTIVE:
    TST [X + 7]
    BEQ ENEMY_RELEASED
    DEC [X + 7]
    JMP ENEMY_TURN_NEXT
ENEMY_RELEASED:
    LDAA [X + 2]
    STAA [ENEMY_KIND]
    CMPA 8
    BNE ENEMY_NO_REGEN
    LDAA [G_TURNS + 1]
    ANDA 3
    BNE ENEMY_NO_REGEN
    LDAA [X + 3]
    CMPA 12
    BCC ENEMY_NO_REGEN
    INC [X + 3]
ENEMY_NO_REGEN:
    LDAA [ENEMY_KIND]
    CMPA 1
    BNE ENEMY_AWAKE
    LDAA [G_TURNS + 1]
    ANDA 1
    BEQ ENEMY_AWAKE
    JMP ENEMY_TURN_NEXT
ENEMY_AWAKE:
    LDAA [X]
    LDAB [X + 1]
    JSR VISIBLE_CELL
    TST [X]
    BEQ ENEMY_MEMORY
    LDAA [ENEMY_KIND]
    CMPA 14
    BEQ ENEMY_RANGED
    CMPA 12
    BNE ENEMY_NOT_RANGED
ENEMY_RANGED:
    JSR ENEMY_POINTER
    LDAA [X]
    CMPA [G_X]
    BEQ ENEMY_SHOOT
    LDAA [X + 1]
    CMPA [G_Y]
    BNE ENEMY_NOT_RANGED
ENEMY_SHOOT:
    JSR ENEMY_STRIKE
    LDAA [ENEMY_KIND]
    CMPA 14
    BNE ENEMY_ARROW_MESSAGE
    LDAA 31
    BRA ENEMY_RANGED_MESSAGE
ENEMY_ARROW_MESSAGE:
    LDAA 15
ENEMY_RANGED_MESSAGE:
    STAA [G_MESSAGE]
    JMP ENEMY_TURN_NEXT
ENEMY_NOT_RANGED:
    JSR ENEMY_POINTER
    LDAA [G_X]
    STAA [X + 4]
    LDAA [G_Y]
    STAA [X + 5]
ENEMY_MEMORY:
    JSR ENEMY_POINTER
    LDAA [X + 4]
    CMPA 255
    BNE ENEMY_HAS_TARGET
    JMP ENEMY_TURN_NEXT
ENEMY_HAS_TARGET:
    LDAA [ENEMY_KIND]
    CMPA 15
    BEQ ENEMY_THIEF_TARGET
    CMPA 9
    BNE ENEMY_NOT_FLEEING
ENEMY_THIEF_TARGET:
    TST [X + 6]
    BEQ ENEMY_NOT_FLEEING
    LDAA MAP_WIDTH - 1
    LDAB [X]
    CMPB [G_X]
    BHI FLEE_X
    CLRA
FLEE_X:
    STAA [X + 4]
    LDAA MAP_HEIGHT - 1
    LDAB [X + 1]
    CMPB [G_Y]
    BHI FLEE_Y
    CLRA
FLEE_Y:
    STAA [X + 5]
ENEMY_NOT_FLEEING:
    LDAA [ENEMY_KIND]
    CMPA 6
    BNE ENEMY_CHASE
    JSR RANDOM
    ANDA 3
    BNE BAT_CHASE
    JSR RANDOM
    ANDA 3
    TAB
    LDX DIRECTION_DX
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    STAA [NX]
    LDX DIRECTION_DY
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    STAA [NY]
    JSR ENEMY_POINTER
    LDAA [NX]
    ADDA [X]
    STAA [NX]
    LDAA [NY]
    ADDA [X + 1]
    STAA [NY]
    JSR ENEMY_STEP
    JMP ENEMY_TURN_NEXT
BAT_CHASE:
    JSR ENEMY_POINTER
ENEMY_CHASE:
    LDAA [X]
    STAA [NX]
    LDAB [X + 1]
    STAB [NY]
    CMPA [X + 4]
    BEQ ENEMY_TRY_Y
    BCS ENEMY_GO_RIGHT
    DEC [NX]
    BRA ENEMY_X_READY
ENEMY_GO_RIGHT:
    INC [NX]
ENEMY_X_READY:
    JSR ENEMY_STEP
    TSTA
    BNE ENEMY_TURN_NEXT
    JSR ENEMY_POINTER
    LDAA [X]
    STAA [NX]
ENEMY_TRY_Y:
    LDAA [X + 1]
    CMPA [X + 5]
    BEQ ENEMY_TARGET_REACHED
    BCS ENEMY_GO_DOWN
    DEC [NY]
    BRA ENEMY_Y_READY
ENEMY_GO_DOWN:
    INC [NY]
ENEMY_Y_READY:
    JSR ENEMY_STEP
    BRA ENEMY_TURN_NEXT
ENEMY_TARGET_REACHED:
    LDAA 255
    STAA [X + 4]
    STAA [X + 5]
ENEMY_TURN_NEXT:
    INC [E_INDEX]
    LDAA [E_INDEX]
    CMPA MAX_ENEMIES
    BEQ ENEMIES_DONE
    JMP ENEMY_TURN_LOOP
ENEMIES_DONE:
    RTS
ENEMY_STEP:
    JSR WALKABLE
    TSTA
    BNE FAR_ENEMY_345_0
    JMP ENEMY_STEP_NO
FAR_ENEMY_345_0:
    LDAA [NX]
    CMPA [G_X]
    BEQ FAR_ENEMY_348_0
    JMP ENEMY_EMPTY
FAR_ENEMY_348_0:
    LDAA [NY]
    CMPA [G_Y]
    BEQ FAR_ENEMY_351_0
    JMP ENEMY_EMPTY
FAR_ENEMY_351_0:
ENEMY_STRIKE:
    JSR ENEMY_POINTER
    LDAB [X + 2]
    STAB [CANDIDATE]
    DECB
    LDX ENEMY_ATTACK
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [X]
    ADDA [G_DIFFICULTY]
    DECA
    SUBA [G_DEFENSE]
    BHI ENEMY_DAMAGE_POSITIVE
    LDAA 1
ENEMY_DAMAGE_POSITIVE:
    STAA [DAMAGE]
    LDAA [G_HP]
    SUBA [DAMAGE]
    BHI ENEMY_DAMAGE_ALIVE
    CLRA
ENEMY_DAMAGE_ALIVE:
    STAA [G_HP]
    LDAA 1
    STAA [G_MESSAGE]
    LDAA [CANDIDATE]
    CMPA 10
    BNE STRIKE_NOT_POISON
    LDAA 6
    STAA [G_POISON]
    CLR [G_POISON_TICK]
    LDAA 12
    STAA [G_MESSAGE]
    JMP ENEMY_STEP_YES
STRIKE_NOT_POISON:
    CMPA 11
    BNE STRIKE_NOT_RUST
    TST [G_DEFENSE]
    BNE FAR_TURNS_501
    JMP ENEMY_STEP_YES
FAR_TURNS_501:
    DEC [G_DEFENSE]
    DEC [G_ARMOR]
    TST [G_DEFENSE]
    BNE RUST_MESSAGE
    CLR [G_ARMOR]
RUST_MESSAGE:
    LDAA 13
    STAA [G_MESSAGE]
    JMP ENEMY_STEP_YES
STRIKE_NOT_RUST:
    CMPA 9
    BNE STRIKE_NOT_THEFT
    JSR ENEMY_POINTER
    TST [X + 6]
    BEQ FAR_TURNS_700
    JMP ENEMY_STEP_YES
FAR_TURNS_700:
    INC [X + 6]
    LDAB [G_GOLD + 1]
    LDAA [G_GOLD]
    SUBB ((10) & 255)
    SBCA ((10) >> 8)
    BCC THEFT_GOLD
    CLRA
    CLRB
THEFT_GOLD:
    STAB [G_GOLD + 1]
    STAA [G_GOLD]
    LDAA 14
    STAA [G_MESSAGE]
    JMP ENEMY_STEP_YES
STRIKE_NOT_THEFT:
    CMPA 15
    BNE STRIKE_NOT_NYMPH
    JSR ENEMY_POINTER
    TST [X + 6]
    BNE NYMPH_DONE
    LDX G_BAG
NYMPH_FIND_ITEM:
    LDAA [X]
    BEQ NYMPH_NEXT_SLOT
    CMPA 22
    BNE NYMPH_STEAL
NYMPH_NEXT_SLOT:
    INX
    CPX G_BAG + 6
    BNE NYMPH_FIND_ITEM
    BRA NYMPH_DONE
NYMPH_STEAL:
    CLR [X]
    JSR ENEMY_POINTER
    INC [X + 6]
    LDAA 32
    STAA [G_MESSAGE]
NYMPH_DONE:
    JMP ENEMY_STEP_YES
STRIKE_NOT_NYMPH:
    CMPA 13
    BNE STRIKE_NOT_VAMPIRE
    JSR RANDOM
    ANDA 3
    BNE VAMPIRE_DONE
    LDAA [G_MAX_HP]
    CMPA 8
    BLS VAMPIRE_DONE
    DEC [G_MAX_HP]
    LDAA [G_HP]
    CMPA [G_MAX_HP]
    BLS VAMPIRE_MESSAGE
    LDAA [G_MAX_HP]
    STAA [G_HP]
VAMPIRE_MESSAGE:
    LDAA 30
    STAA [G_MESSAGE]
VAMPIRE_DONE:
    JMP ENEMY_STEP_YES
STRIKE_NOT_VAMPIRE:
    CMPA 4
    BEQ FAR_TURNS_701
    JMP ENEMY_STEP_YES
FAR_TURNS_701:
    LDAA [G_FOOD]
    SUBA 3
    BCC WRAITH_FOOD
    CLRA
WRAITH_FOOD:
    STAA [G_FOOD]
    JMP ENEMY_STEP_YES
ENEMY_EMPTY:
    JSR FIND_ENEMY
    TSTA
    BEQ FAR_ENEMY_426_0
    JMP ENEMY_STEP_NO
FAR_ENEMY_426_0:
    JSR ENEMY_POINTER
    LDAA [NX]
    STAA [X]
    LDAA [NY]
    STAA [X + 1]
ENEMY_STEP_YES:
    LDAA 1
    RTS
ENEMY_STEP_NO:
    CLRA
    RTS
SAFE_WALK:
    CLR [SAFE_FLAG]
    TST [G_MESSAGE]
    BEQ SAFE_NO_MESSAGE
    RTS
SAFE_NO_MESSAGE:
    LDAA [G_FOOD]
    CMPA 40
    BHI LONG_T302
    JMP SAFE_DONE
LONG_T302:
    LDAA [G_MODE]
    CMPA 1
    BEQ LONG_T305
    JMP SAFE_DONE
LONG_T305:
    CLR [E_INDEX]
SAFE_ENEMY_LOOP:
    JSR ENEMY_POINTER
    TST [X + 3]
    BEQ SAFE_ENEMY_NEXT
    LDAA [X]
    LDAB [X + 1]
    JSR VISIBLE_CELL
    TST [X]
    BEQ LONG_T315
    JMP SAFE_DONE
LONG_T315:
SAFE_ENEMY_NEXT:
    INC [E_INDEX]
    LDAA [E_INDEX]
    CMPA MAX_ENEMIES
    BNE SAFE_ENEMY_LOOP
    LDAA [G_X]
    STAA [NX]
    LDAA [G_Y]
    STAA [NY]
    CLR [NEIGHBORS]
    CLR [CHECK_X]
SAFE_NEIGHBORS:
    LDAA [G_X]
    LDAB [G_Y]
    LDX DIRECTION_DX
    PSHB
    LDAB [CHECK_X]
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    ADDA [X]
    STAA [NX]
    LDX DIRECTION_DY
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    PULB
    ADDB [X]
    STAB [NY]
    JSR WALKABLE
    TSTA
    BEQ SAFE_NEIGHBOR_NEXT
    INC [NEIGHBORS]
SAFE_NEIGHBOR_NEXT:
    INC [CHECK_X]
    LDAA [CHECK_X]
    CMPA 4
    BNE SAFE_NEIGHBORS
    LDAA [NEIGHBORS]
    CMPA 2
    BEQ LONG_T353
    JMP SAFE_DONE
LONG_T353:
    LDAA [G_X]
    STAA [NX]
    LDAA [G_Y]
    STAA [NY]
    LDAB [LAST_DIRECTION]
    DECB
    LDX DIRECTION_DX
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [NX]
    ADDA [X]
    STAA [NX]
    LDX DIRECTION_DY
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [NY]
    ADDA [X]
    STAA [NY]
    TAB
    LDAA [NX]
    JSR CELL
    CMPA 129
    BEQ LONG_T374
    JMP SAFE_DONE
LONG_T374:
    JSR FIND_ITEM
    TSTA
    BEQ LONG_T377
    JMP SAFE_DONE
LONG_T377:
    INC [SAFE_FLAG]
SAFE_DONE:
    RTS
