; SPDX-License-Identifier: MIT
; JR-200 text UI, viewport, and PCG overlays.
MENU_INPUT:
    LDAA [G_KEY]
    CMPA 6
    BEQ MENU_BACK
    LDAA [G_MODE]
    CMPA 6
    BEQ MENU_HELP_CLOSE
    LDAA [G_KEY]
    CMPA 1
    BEQ MENU_UP
    CMPA 2
    BEQ MENU_DOWN
    CMPA 5
    BEQ MENU_CONFIRM
    RTS
MENU_UP:
MENU_DOWN:
    LDAA [G_MODE]
    CMPA 3
    BEQ BAG_LIMIT
    CMPA 4
    BEQ ITEM_LIMIT
    LDAA [G_CONTEXT]
    ADDA 6
    BRA MENU_LIMIT
BAG_LIMIT:
    LDAA 6
    BRA MENU_LIMIT
ITEM_LIMIT:
    LDAA 2
MENU_LIMIT:
    TAB
    LDAA [G_MENU]
    JSR WRAP_CURSOR
    STAA [G_MENU]
MENU_INPUT_DONE:
    RTS
; A=current index, B=last index, G_KEY=up/down. Shared by every list.
WRAP_CURSOR:
    STAB [TEMP]
    LDAB [G_KEY]
    DECB
    BEQ WRAP_UP
    INCA
    CMPA [TEMP]
    BLS WRAP_DONE
    CLRA
    RTS
WRAP_UP:
    TSTA
    BNE WRAP_DECREMENT
    LDAA [TEMP]
    RTS
WRAP_DECREMENT:
    DECA
WRAP_DONE:
    RTS
MENU_BACK:
    LDAA [G_MODE]
    CMPA 4
    BNE LONG_U45
    JMP MENU_TO_BAG
LONG_U45:
    CMPA 3
    BNE FAR_UI_26_0
    JMP MENU_TO_MAIN
FAR_UI_26_0:
    CMPA 6
    BNE FAR_UI_26_1
    JMP MENU_TO_MAIN
FAR_UI_26_1:
    LDAA 1
    STAA [G_MODE]
    RTS
MENU_TO_BAG:
    LDAA 3
    STAA [G_MODE]
    LDAA [G_SLOT]
    STAA [G_MENU]
    RTS
MENU_HELP_CLOSE:
    LDAA [G_KEY]
    CMPA 5
    BNE MENU_INPUT_DONE
MENU_TO_MAIN:
    LDAA 2
    STAA [G_MODE]
    CLR [G_MENU]
    RTS
MENU_CONFIRM:
    LDAA [G_MODE]
    CMPA 3
    BEQ BAG_CONFIRM
    CMPA 4
    BNE FAR_UI_14_0
    JMP ITEM_CONFIRM
FAR_UI_14_0:
    LDAA [G_MENU]
    TST [G_CONTEXT]
    BEQ MAIN_CHOICE
    TSTA
    BNE MAIN_HAS_STAIRS
    JMP STAIRS_ACTION
MAIN_HAS_STAIRS:
    DECA
MAIN_CHOICE:
    TSTA
    BEQ OPEN_BAG
    CMPA 1
    BEQ CHOOSE_WAIT
    CMPA 2
    BEQ CHOOSE_NORMAL_INSPECT
    CMPA 3
    BEQ CHOOSE_SUSPEND
    CMPA 4
    BEQ CHOOSE_HELP
    CMPA 5
    BEQ CHOOSE_SEARCH
    JMP MENU_BACK
CHOOSE_HELP:
    LDAA 6
    STAA [G_MODE]
    RTS
CHOOSE_SEARCH:
    LDAA 1
    STAA [G_MODE]
    JMP SEARCH_ACTION
OPEN_BAG:
    LDAA 3
    STAA [G_MODE]
    CLR [G_MENU]
    RTS
CHOOSE_WAIT:
    LDAA 1
    STAA [G_MODE]
    CLR [G_MESSAGE]
    JMP COMMIT_TURN
CHOOSE_NORMAL_INSPECT:
    CLR [G_WAND_SLOT]
CHOOSE_INSPECT:
    LDAA 5
    STAA [G_MODE]
    LDAA [G_X]
    STAA [G_INSPECT_X]
    LDAA [G_Y]
    STAA [G_INSPECT_Y]
    RTS
CHOOSE_SUSPEND:
    LDAA 7
    STAA [G_MODE]
    LDAA 1
    STAA [G_SUSPEND]
    RTS
BAG_CONFIRM:
    LDAA [G_MENU]
    CMPA 6
    BNE FAR_UI_26_2
    JMP MENU_TO_MAIN
FAR_UI_26_2:
    LDAA [G_MENU]
    STAA [G_SLOT]
    JSR BAG_ITEM
    TSTA
    BEQ BAG_CONFIRM_DONE
    LDAA 4
    STAA [G_MODE]
    CLR [G_MENU]
BAG_CONFIRM_DONE:
    RTS
ITEM_CONFIRM:
    LDAA [G_MENU]
    BEQ ITEM_USE
    CMPA 1
    BEQ LONG_U133
    JMP MENU_TO_BAG
LONG_U133:
    JMP DISCARD_ITEM
ITEM_USE:
    JMP USE_ITEM
INSPECT_MOVE:
    LDAA [G_KEY]
    CMPA 5
    BNE INSPECT_NOT_CONFIRM
    JMP INSPECT_CONFIRM
INSPECT_NOT_CONFIRM:
    CMPA 6
    BEQ INSPECT_CLOSE
    CMPA 11
    BEQ INSPECT_DONE
    LDAA [G_INSPECT_X]
    LDAB [G_KEY]
    DECB
    LDX DIRECTION_DX
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    ADDA [X]
    CMPA MAP_WIDTH
    BCC INSPECT_DONE
    STAA [NX]
    LDAA [G_INSPECT_Y]
    LDX DIRECTION_DY
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    ADDA [X]
    CMPA MAP_HEIGHT
    BCC INSPECT_DONE
    STAA [NY]
    TAB
    LDAA [NX]
    JSR VISIBLE_CELL
    TST [X]
    BEQ INSPECT_DONE
    LDAA [NX]
    STAA [G_INSPECT_X]
    LDAA [NY]
    STAA [G_INSPECT_Y]
INSPECT_DONE:
    RTS
INSPECT_CLOSE:
    CLR [G_WAND_SLOT]
    LDAA 1
    STAA [G_MODE]
    RTS
RENDER_SCREEN:
    JSR RENDER_FRAME
    JMP PRESENT
RENDER_FRAME:
    JSR SELECT_PCG_BANK
    JSR CLEAR
    LDAA [G_MODE]
    BEQ RENDER_TITLE
    CMPA 8
    BCS LONG_U179
    JMP RENDER_END
LONG_U179:
    CMPA 7
    BNE FAR_UI_200
    JMP RENDER_SUSPEND
FAR_UI_200:
    CMPA 6
    BNE FAR_UI_208
    JMP RENDER_HELP
FAR_UI_208:
    CMPA 2
    BEQ RENDER_MENU_JUMP
    CMPA 3
    BEQ RENDER_BAG_JUMP
    CMPA 4
    BEQ RENDER_ITEM_JUMP
    JSR RENDER_HUD
    JSR RENDER_MAP
    LDAA [G_MODE]
    CMPA 5
    BNE RENDER_MESSAGE
    JMP RENDER_INSPECT
RENDER_MESSAGE:
    LDAB [G_MESSAGE]
    ASLB
    LDX MESSAGES
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    JSR LOAD_STRING
    LDAB ((FRAMEBUFFER + 704) & 255)
    LDAA ((FRAMEBUFFER + 704) >> 8)
    JSR TEXT
    RTS
RENDER_MENU_JUMP:
    JMP RENDER_MENU
RENDER_BAG_JUMP:
    JMP RENDER_BAG
RENDER_ITEM_JUMP:
    JMP RENDER_ITEM
RENDER_TITLE:
    JSR DRAW_TITLE_ART
    LDX S_GOAL
    LDAB ((FRAMEBUFFER + 549) & 255)
    LDAA ((FRAMEBUFFER + 549) >> 8)
    JSR TEXT
    LDAA [G_DIFFICULTY]
    STAA [G_MENU]
    LDX DIFFICULTY_NAMES
    STX [UI_PTR]
    LDAA 3
    STAA [COUNT]
    LDAA 9
    STAA [UI_ROW]
    JSR RENDER_CHOICES
    LDX S_KEYS
    LDAB ((FRAMEBUFFER + 736) & 255)
    LDAA ((FRAMEBUFFER + 736) >> 8)
    JMP TEXT
; The bank is switched only at title/game transitions, never per terrain cell.
SELECT_PCG_BANK:
    LDAA 2
    LDX TILES
    LDAB TILES_END - TILES
    TST [G_MODE]
    BNE SELECT_BANK_READY
    LDAA 1
    LDX TITLE_TILES
    LDAB ((TITLE_TILES_END - TITLE_TILES) & 255)
SELECT_BANK_READY:
    CMPA [PCG_BANK]
    BEQ SELECT_BANK_DONE
    STAA [PCG_BANK]
    STX [TEXT_SRC]
    LDX JR200_PCG_BANK1
    STX [TEXT_DEST]
    JMP COPY_BYTES
SELECT_BANK_DONE:
    RTS
; High bytes are PCG; 1..126 skip blanks; 127 repeats (count, code); zero ends.
DRAW_TITLE_ART:
    LDX FRAMEBUFFER
    STX [TEXT_DEST]
    LDX TITLE_ART
TITLE_ART_NEXT:
    LDAA [X]
    BEQ TITLE_ART_DONE
    INX
    CMPA 127
    BEQ TITLE_ART_RUN
    STX [TEXT_SRC]
    TSTA
    BMI TITLE_ART_PIXEL
    TAB
    CLRA
    ADDB [TEXT_DEST + 1]
    ADCA [TEXT_DEST]
    STAB [TEXT_DEST + 1]
    STAA [TEXT_DEST]
    BRA TITLE_ART_ADVANCE
TITLE_ART_PIXEL:
    LDX [TEXT_DEST]
    STAA [X]
    INX
    STX [TEXT_DEST]
TITLE_ART_ADVANCE:
    LDX [TEXT_SRC]
    BRA TITLE_ART_NEXT
TITLE_ART_DONE:
    RTS
TITLE_ART_RUN:
    LDAB [X]
    LDAA [X + 1]
    INX
    INX
    STX [TEXT_SRC]
    LDX [TEXT_DEST]
TITLE_ART_REPEAT:
    STAA [X]
    INX
    DECB
    BNE TITLE_ART_REPEAT
    STX [TEXT_DEST]
    BRA TITLE_ART_ADVANCE
; Change one sparkle character every 256 title polls without redrawing VRAM.
TITLE_SHIMMER:
    TST [G_SEED + 1]
    BNE TITLE_SHIMMER_DONE
    LDX TITLE_SPARK_FRAMES
    LDAA [G_SEED]
    BITA 1
    BEQ TITLE_SPARK_READY
    ADDX8 8
TITLE_SPARK_READY:
    STX [TEXT_SRC]
    LDX TITLE_SPARK_ADDRESS
    STX [TEXT_DEST]
    LDAB 8
    JMP COPY_BYTES
TITLE_SHIMMER_DONE:
    RTS
RENDER_SUSPEND:
    LDX S_SUSPENDED
    LDAB ((FRAMEBUFFER + 138) & 255)
    LDAA ((FRAMEBUFFER + 138) >> 8)
    JSR TEXT
    LDX S_RESUME
    LDAB ((FRAMEBUFFER + 261) & 255)
    LDAA ((FRAMEBUFFER + 261) >> 8)
    JMP TEXT
RENDER_HELP:
    LDX HELP_LINES
    STX [UI_PTR]
    LDAA 7
    STAA [COUNT]
    LDAA 1
    STAA [UI_ROW]
    JSR RENDER_LINES
    LDX S_BACK
    LDAB ((FRAMEBUFFER + 736) & 255)
    LDAA ((FRAMEBUFFER + 736) >> 8)
    JMP TEXT
RENDER_END:
    LDX S_DEAD
    LDAA [G_MODE]
    CMPA 8
    BEQ RENDER_END_TITLE
    LDX S_WON
RENDER_END_TITLE:
    LDAB ((FRAMEBUFFER + 135) & 255)
    LDAA ((FRAMEBUFFER + 135) >> 8)
    JSR TEXT
    LDX S_END
    LDAB ((FRAMEBUFFER + 262) & 255)
    LDAA ((FRAMEBUFFER + 262) >> 8)
    JSR TEXT
    LDX S_GOLD
    LDAB ((FRAMEBUFFER + 394) & 255)
    LDAA ((FRAMEBUFFER + 394) >> 8)
    JSR TEXT
    LDX FRAMEBUFFER + 399
    JSR RENDER_GOLD
    TST [G_MESSAGE]
    BEQ END_WITHOUT_CAUSE
    JSR RENDER_MESSAGE
END_WITHOUT_CAUSE:
    JMP RENDER_HUD
RENDER_HUD:
    LDX S_FLOOR
    LDAB ((FRAMEBUFFER + 0) & 255)
    LDAA ((FRAMEBUFFER + 0) >> 8)
    JSR TEXT
    LDAA [G_FLOOR]
    INCA
    LDX FRAMEBUFFER + 1
    JSR NUMBER
    LDX S_HP
    LDAB ((FRAMEBUFFER + 5) & 255)
    LDAA ((FRAMEBUFFER + 5) >> 8)
    JSR TEXT
    LDAA [G_HP]
    LDX FRAMEBUFFER + 8
    JSR NUMBER
    LDAA 47
    LDX FRAMEBUFFER + 11
    JSR GLYPH
    LDAA [G_MAX_HP]
    LDX FRAMEBUFFER + 12
    JSR NUMBER
    LDX S_FOOD
    LDAB ((FRAMEBUFFER + 17) & 255)
    LDAA ((FRAMEBUFFER + 17) >> 8)
    JSR TEXT
    LDAA [G_FOOD]
    LDX FRAMEBUFFER + 20
    JSR NUMBER
    LDX S_LEVEL
    LDAB ((FRAMEBUFFER + 26) & 255)
    LDAA ((FRAMEBUFFER + 26) >> 8)
    JSR TEXT
    LDAA [G_LEVEL]
    LDX FRAMEBUFFER + 28
    JSR NUMBER
    TST [G_POISON]
    BEQ HUD_DONE
    LDAA 80
    LDX FRAMEBUFFER + 31
    JSR GLYPH
HUD_DONE:
    JMP RENDER_STATUS_LINE
NUMBER:
    STAA [NUM]
    STX [NUM_DEST]
    LDAA 48
    STAA [DIGIT]
NUMBER_HUNDREDS:
    LDAA [NUM]
    CMPA 100
    BCS NUMBER_HUNDREDS_DONE
    SUBA 100
    STAA [NUM]
    INC [DIGIT]
    BRA NUMBER_HUNDREDS
NUMBER_HUNDREDS_DONE:
    LDAA [DIGIT]
    JSR GLYPH
    LDX [NUM_DEST]
    INX
    STX [NUM_DEST]
    LDAA 48
    STAA [DIGIT]
NUMBER_TENS:
    LDAA [NUM]
    CMPA 10
    BCS NUMBER_TENS_DONE
    SUBA 10
    STAA [NUM]
    INC [DIGIT]
    BRA NUMBER_TENS
NUMBER_TENS_DONE:
    LDAA [DIGIT]
    JSR GLYPH
    LDX [NUM_DEST]
    INX
    LDAA [NUM]
    ADDA 48
    JMP GLYPH
RENDER_MAP:
    JSR POLL_KEY
    LDAA [G_MODE]
    CMPA 5
    BNE VIEW_PLAYER_XY
    LDAA [G_INSPECT_X]
    LDAB [G_INSPECT_Y]
    BRA VIEW_CALCULATE
VIEW_PLAYER_XY:
    LDAA [G_X]
    LDAB [G_Y]
VIEW_CALCULATE:
    SUBA 16
    BCC VIEW_X_POSITIVE
    CLRA
VIEW_X_POSITIVE:
    CMPA MAP_WIDTH - 32
    BLS VIEW_X_READY
    LDAA MAP_WIDTH - 32
VIEW_X_READY:
    STAA [VIEW_X]
    TBA
    SUBA 10
    BCC VIEW_Y_POSITIVE
    CLRA
VIEW_Y_POSITIVE:
    CMPA MAP_HEIGHT - 20
    BLS VIEW_Y_READY
    LDAA MAP_HEIGHT - 20
VIEW_Y_READY:
    STAA [VIEW_Y]
    STAA [ROW]
    LDX FRAMEBUFFER + 64
    STX [DRAW]
MAP_ROW:
    LDAA [VIEW_X]
    STAA [COL]
    LDAB [ROW]
    JSR CELL
    LDAB 32
; Decode sequential nibbles/bits; initialize their addresses once per row.
MAP_COLUMN:
    LDX [CELL_BIT_PTR]
    LDAA [X]
    BITA [CELL_MASK]
    BEQ TILE_UNKNOWN
    LDX [CELL_PACKED]
    LDAA [COL]
    BITA 1
    BEQ MAP_LOAD_LOW
    LDAA [X]
    LSRA
    LSRA
    LSRA
    LSRA
    BRA MAP_LOW_NIBBLE
MAP_LOAD_LOW:
    LDAA [X]
MAP_LOW_NIBBLE:
    ANDA 15
    CMPA 5
    BEQ TILE_WALL
    CMPA 6
    BCS TILE_NORMAL
    CMPA 8
    BCS TILE_FLOOR
    LDAA 25
    BRA TILE_READY
TILE_WALL:
    CLRA
    BRA TILE_NORMAL
TILE_FLOOR:
    LDAA 1
TILE_NORMAL:
    INCA
    BRA TILE_READY
TILE_UNKNOWN:
    TSTA
    BNE TILE_SINGLE_UNKNOWN
    LDAA 128
    LDX [DRAW]
MAP_BLANK_RUN:
    STAA [X]
    INX
    INC [COL]
    DECB
    BEQ MAP_BLANK_ROW_DONE
    ASL [CELL_MASK]
    BNE MAP_BLANK_RUN
    STX [DRAW]
    STAB [COUNT]
    LDAA [COL]
    LDAB [ROW]
    JSR CELL
    LDAB [COUNT]
    JMP MAP_COLUMN
MAP_BLANK_ROW_DONE:
    STX [DRAW]
    JMP MAP_NEXT_ROW
TILE_SINGLE_UNKNOWN:
    CLRA
TILE_READY:
    ORAA 128
    LDX [DRAW]
    STAA [X]
    INX
    STX [DRAW]
    ASL [CELL_MASK]
    BNE MAP_NEXT_MASK
    INC [CELL_BIT_PTR + 1]
    LDAA 1
    STAA [CELL_MASK]
; Aligned terrain/bit rows cross a page only after their last column.
MAP_NEXT_MASK:
    INC [COL]
    LDAA [COL]
    BITA 1
    BNE MAP_NEXT_PACKED
    INC [CELL_PACKED + 1]
MAP_NEXT_PACKED:
    DECB
    BEQ MAP_NEXT_ROW
    JMP MAP_COLUMN
MAP_NEXT_ROW:
    INC [ROW]
    LDAA [ROW]
    SUBA [VIEW_Y]
    CMPA 20
    BEQ MAP_TERRAIN_DONE
    JMP MAP_ROW
MAP_TERRAIN_DONE:
    LDX FLOORS + ITEM_START
    STX [ITEM_PTR]
MAP_ITEMS:
    LDX [ITEM_PTR]
    TST [X + 2]
    BEQ MAP_ITEM_NEXT
    LDAA [X]
    STAA [NX]
    LDAA [X + 1]
    STAA [NY]
    LDAA [X + 2]
    CMPA 17
    BCS MAP_OLD_ITEM
    LDAA 29
    LDAB [X + 2]
    CMPB 21
    BCS MAP_TOOL_TILE
    INCA
MAP_TOOL_TILE:
    JMP MAP_ITEM_TILE
MAP_OLD_ITEM:
    CMPA 14
    BEQ ITEM_POTION_TILE
    BHI ITEM_NEW_SCROLL_TILE
    CMPA 7
    BCS ITEM_CONSUMABLE_TILE
    CMPA 10
    BCS ITEM_WEAPON_TILE
    CMPA 13
    BCS ITEM_ARMOR_TILE
    LDAA 12
    BRA MAP_ITEM_TILE
ITEM_WEAPON_TILE:
    LDAA 10
    BRA MAP_ITEM_TILE
ITEM_ARMOR_TILE:
    LDAA 11
    BRA MAP_ITEM_TILE
ITEM_NEW_SCROLL_TILE:
    LDAA 9
    BRA MAP_ITEM_TILE
ITEM_CONSUMABLE_TILE:
    CMPA 1
    BEQ ITEM_FOOD_TILE
    CMPA 5
    BCS ITEM_POTION_TILE
    LDAA 9
    BRA MAP_ITEM_TILE
ITEM_FOOD_TILE:
    LDAA 7
    BRA MAP_ITEM_TILE
ITEM_POTION_TILE:
    LDAA 8
MAP_ITEM_TILE:
    STAA [TILE]
    JSR OVERLAY_VISIBLE
MAP_ITEM_NEXT:
    LDX [ITEM_PTR]
    ADDX8 3
    STX [ITEM_PTR]
    CPX FLOORS + FLOOR_DATA_END
    BEQ FAR_UI_900
    JMP MAP_ITEMS
FAR_UI_900:
    CLR [E_INDEX]
MAP_ENEMIES:
    JSR ENEMY_POINTER
    TST [X + 3]
    BEQ MAP_ENEMY_NEXT
    LDAA [X]
    STAA [NX]
    LDAA [X + 1]
    STAA [NY]
    LDAA [X + 2]
    CMPA 13
    BCS ENEMY_TILE_OLD
    INCA
ENEMY_TILE_OLD:
    ADDA 12
    STAA [TILE]
    JSR OVERLAY_VISIBLE
MAP_ENEMY_NEXT:
    INC [E_INDEX]
    LDAA [E_INDEX]
    CMPA MAX_ENEMIES
    BNE MAP_ENEMIES
    LDAA [G_X]
    STAA [NX]
    LDAA [G_Y]
    STAA [NY]
    JSR TILE_DESTINATION
    LDAA 6
    JSR DRAW_TILE
    RTS
OVERLAY_VISIBLE:
    LDAA [NX]
    SUBA [VIEW_X]
    CMPA 32
    BCC OVERLAY_DONE
    LDAA [NY]
    SUBA [VIEW_Y]
    CMPA 20
    BCC OVERLAY_DONE
    LDAA [NX]
    LDAB [NY]
    JSR VISIBLE_CELL
    TST [X]
    BEQ OVERLAY_DONE
    JSR TILE_DESTINATION
    LDAA [TILE]
    JSR DRAW_TILE
OVERLAY_DONE:
    RTS
TILE_DESTINATION:
    LDAA [NY]
    SUBA [VIEW_Y]
    ADDA 2
    LDAB 32
    JSR MULTIPLY
    ADDB ((FRAMEBUFFER) & 255)
    ADCA ((FRAMEBUFFER) >> 8)
    STAB [DRAW + 1]
    STAA [DRAW]
    LDAA [NX]
    SUBA [VIEW_X]
    ADDA [DRAW + 1]
    STAA [DRAW + 1]
    BCC TILE_DESTINATION_DONE
    INC [DRAW]
TILE_DESTINATION_DONE:
    RTS
DRAW_TILE:
    ORAA 128
    LDX [DRAW]
    STAA [X]
    INX
    STX [DRAW]
    RTS
LOAD_STRING:
    LDX [X]
    RTS
RENDER_MENU:
    JSR RENDER_STATS
    LDAA [G_X]
    LDAB [G_Y]
    JSR CELL
    ANDA 127
    CLR [G_CONTEXT]
    CMPA 3
    BNE MENU_PLAIN
MENU_CONTEXT:
    INC [G_CONTEXT]
    LDX MAIN_NAMES
    LDAA 8
    BRA MENU_DRAW
MENU_PLAIN:
    LDX MAIN_NAMES + 2
    LDAA 7
MENU_DRAW:
    STX [UI_PTR]
    STAA [COUNT]
    LDAA 1
    STAA [UI_ROW]
    JSR RENDER_CHOICES
    LDX S_MENU_KEYS
    LDAB ((FRAMEBUFFER + 704) & 255)
    LDAA ((FRAMEBUFFER + 704) >> 8)
    JMP TEXT
RENDER_BAG:
    JSR RENDER_STATS
    LDAA 1
    STAA [UI_ROW]
    CLR [G_SLOT]
BAG_DRAW_LOOP:
    JSR BAG_ITEM
    JSR ITEM_NAME
    LDAA [UI_ROW]
    LDAB 64
    JSR MULTIPLY
    ADDB ((FRAMEBUFFER + 3) & 255)
    ADCA ((FRAMEBUFFER + 3) >> 8)
    JSR TEXT
    LDAA [G_SLOT]
    CMPA [G_MENU]
    BNE BAG_DRAW_NEXT
    JSR DRAW_SELECTION
BAG_DRAW_NEXT:
    INC [UI_ROW]
    INC [G_SLOT]
    LDAA [G_SLOT]
    CMPA 6
    BNE BAG_DRAW_LOOP
    LDX S_BACK
    LDAB ((FRAMEBUFFER + 451) & 255)
    LDAA ((FRAMEBUFFER + 451) >> 8)
    JSR TEXT
    LDAA [G_MENU]
    CMPA 6
    BNE BAG_NO_BACK_CURSOR
    JSR DRAW_SELECTION
BAG_NO_BACK_CURSOR:
    LDX S_MENU_KEYS
    LDAB ((FRAMEBUFFER + 704) & 255)
    LDAA ((FRAMEBUFFER + 704) >> 8)
    JMP TEXT
ITEM_NAME:
    CMPA 17
    BCS ITEM_NAME_BELOW_17
    JMP ITEM_NAME_RAW
ITEM_NAME_BELOW_17:
    CMPA 2
    BCC ITEM_NAME_AT_LEAST_2
    JMP ITEM_NAME_RAW
ITEM_NAME_AT_LEAST_2:
    CMPA 14
    BCC ITEM_NAME_MAGIC
    CMPA 7
    BCS ITEM_NAME_MAGIC
    JMP ITEM_NAME_RAW
ITEM_NAME_MAGIC:
    STAA [ITEM_TYPE]
    JSR MAGIC_INDEX
    LDX BITS
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAA [G_KNOWN]
    BITA [X]
    BEQ ITEM_NAME_UNKNOWN
    LDX G_IDENTITIES
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    LDAB [X]
    ASLB
    LDX EFFECT_NAMES
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    JMP LOAD_STRING
ITEM_NAME_UNKNOWN:
    LDAA [ITEM_TYPE]
ITEM_NAME_RAW:
    TAB
    ASLB
    LDX ITEM_NAMES
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    JMP LOAD_STRING
RENDER_ITEM:
    JSR BAG_ITEM
    JSR ITEM_NAME
    LDAB ((FRAMEBUFFER + 64) & 255)
    LDAA ((FRAMEBUFFER + 64) >> 8)
    JSR TEXT
    LDAA [ITEM_TYPE]
    CMPA 14
    BCC ITEM_NO_COMPARISON
    CMPA 7
    BCS ITEM_NO_COMPARISON
    CMPA 10
    BCC ARMOR_COMPARISON
    LDX S_ATK_SWAP
    LDAB ((FRAMEBUFFER + 128) & 255)
    LDAA ((FRAMEBUFFER + 128) >> 8)
    JSR TEXT
    LDAA [G_ATTACK]
    LDX FRAMEBUFFER + 137
    JSR NUMBER
    LDAA [ITEM_TYPE]
    SUBA 3
    BRA COMPARISON_VALUE
ARMOR_COMPARISON:
    LDX S_DEF_SWAP
    LDAB ((FRAMEBUFFER + 128) & 255)
    LDAA ((FRAMEBUFFER + 128) >> 8)
    JSR TEXT
    LDAA [G_DEFENSE]
    LDX FRAMEBUFFER + 137
    JSR NUMBER
    LDAA [ITEM_TYPE]
    SUBA 9
COMPARISON_VALUE:
    LDX FRAMEBUFFER + 147
    JSR NUMBER
ITEM_NO_COMPARISON:
    LDX ITEM_ACTIONS
    STX [UI_PTR]
    LDAA 3
    STAA [COUNT]
    LDAA 4
    STAA [UI_ROW]
    JSR RENDER_CHOICES
    JMP RENDER_MESSAGE
RENDER_CHOICES:
    CLR [CANDIDATE]
CHOICES_NEXT:
    LDAA [CANDIDATE]
    CMPA [G_MENU]
    BNE CHOICES_UNSELECTED
    JSR DRAW_SELECTION
CHOICES_UNSELECTED:
    JSR RENDER_LINE
    INC [CANDIDATE]
    DEC [COUNT]
    BNE CHOICES_NEXT
    RTS
RENDER_LINES:
    JSR RENDER_LINE
    DEC [COUNT]
    BNE RENDER_LINES
    RTS
RENDER_LINE:
    LDX [UI_PTR]
    JSR LOAD_STRING
    LDAA [UI_ROW]
    LDAB 64
    JSR MULTIPLY
    ADDB ((FRAMEBUFFER + 3) & 255)
    ADCA ((FRAMEBUFFER + 3) >> 8)
    JSR TEXT
    LDX [UI_PTR]
    INX
    INX
    STX [UI_PTR]
    INC [UI_ROW]
    RTS
DRAW_SELECTION:
    LDAA [UI_ROW]
    LDAB 64
    JSR MULTIPLY
    ADDB ((FRAMEBUFFER + 0) & 255)
    ADCA ((FRAMEBUFFER + 0) >> 8)
    STAB [P2 + 1]
    STAA [P2]
    LDX [P2]
    LDAA 0x3E
    JSR GLYPH
    RTS
RENDER_INSPECT:
    LDAA [G_INSPECT_X]
    STAA [NX]
    LDAA [G_INSPECT_Y]
    STAA [NY]
    LDAA [NY]
    SUBA [VIEW_Y]
    CMPA 20
    BCC INSPECT_NAME
    JSR TILE_DESTINATION
    LDX [DRAW]
    LDAA 0x3E
    JSR GLYPH
INSPECT_NAME:
    JSR FIND_ENEMY
    TSTA
    BEQ INSPECT_ITEM
    DECA
    ASLA
    STAA [CANDIDATE]
    TAB
    LDX ENEMY_NAMES
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    JSR LOAD_STRING
    LDAB ((FRAMEBUFFER + 704) & 255)
    LDAA ((FRAMEBUFFER + 704) >> 8)
    JSR TEXT
    LDX [E_PTR]
    LDAA [X + 3]
    LDX FRAMEBUFFER + 720
    JSR NUMBER
    LDX FRAMEBUFFER + 0
    LDAA JR200_CHAR_SPACE
INSPECT_CLEAR_HUD:
    STAA [X]
    INX
    CPX FRAMEBUFFER + 64
    BNE INSPECT_CLEAR_HUD
    LDAB [CANDIDATE]
    LDX ENEMY_TRAITS
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    JSR LOAD_STRING
    LDAB ((FRAMEBUFFER + 0) & 255)
    LDAA ((FRAMEBUFFER + 0) >> 8)
    JMP TEXT
INSPECT_ITEM:
    TST [G_WAND_SLOT]
    BEQ INSPECT_GROUND_ITEM
    LDAA [NX]
    CMPA [G_X]
    BNE INSPECT_GROUND_ITEM
    LDAA [NY]
    CMPA [G_Y]
    BNE INSPECT_GROUND_ITEM
    LDX S_BACK
    BRA INSPECT_TEXT
INSPECT_GROUND_ITEM:
    JSR FIND_ITEM
    TSTA
    BEQ INSPECT_TERRAIN
    JSR ITEM_NAME
    BRA INSPECT_TEXT
INSPECT_TERRAIN:
    LDAA [NX]
    LDAB [NY]
    JSR CELL
    ANDA 127
    CMPA 5
    BNE INSPECT_TILE_TYPE
    CLRA
INSPECT_TILE_TYPE:
    ASLA
    TAB
    LDX TERRAIN_NAMES
    STAB [INDEX_OFFSET + 1]
    ADDX16 INDEX_OFFSET
    JSR LOAD_STRING
INSPECT_TEXT:
    LDAB ((FRAMEBUFFER + 704) & 255)
    LDAA ((FRAMEBUFFER + 704) >> 8)
    JMP TEXT
RENDER_STATS:
    LDX S_STATS
    LDAB ((FRAMEBUFFER + 0) & 255)
    LDAA ((FRAMEBUFFER + 0) >> 8)
    JSR TEXT
    LDAA [G_ATTACK]
    LDX FRAMEBUFFER + 4
    JSR NUMBER
    LDAA [G_DEFENSE]
    LDX FRAMEBUFFER + 12
    JSR NUMBER
    LDX FRAMEBUFFER + 23
RENDER_GOLD:
    STX [NUM_DEST]
    LDAB [G_GOLD + 1]
    LDAA [G_GOLD]
    STAB [GOLD_VALUE + 1]
    STAA [GOLD_VALUE]
    LDAB ((10000) & 255)
    LDAA ((10000) >> 8)
    JSR GOLD_DIGIT
    LDAB ((1000) & 255)
    LDAA ((1000) >> 8)
    JSR GOLD_DIGIT
    LDAA 48
    STAA [DIGIT]
GOLD_HUNDREDS:
    LDAB [GOLD_VALUE + 1]
    LDAA [GOLD_VALUE]
    SUBB ((100) & 255)
    SBCA ((100) >> 8)
    BCS GOLD_REMAINDER
    STAB [GOLD_VALUE + 1]
    STAA [GOLD_VALUE]
    INC [DIGIT]
    BRA GOLD_HUNDREDS
GOLD_REMAINDER:
    ADDB ((100) & 255)
    ADCA ((100) >> 8)
    STAB [NUM]
    JMP NUMBER_HUNDREDS_DONE
GOLD_DIGIT:
    STAB [GOLD_DIVISOR + 1]
    STAA [GOLD_DIVISOR]
    LDAA 48
    STAA [DIGIT]
GOLD_DIGIT_LOOP:
    LDAB [GOLD_VALUE + 1]
    LDAA [GOLD_VALUE]
    SUBB [GOLD_DIVISOR + 1]
    SBCA [GOLD_DIVISOR]
    BCS GOLD_DIGIT_DONE
    STAB [GOLD_VALUE + 1]
    STAA [GOLD_VALUE]
    INC [DIGIT]
    BRA GOLD_DIGIT_LOOP
GOLD_DIGIT_DONE:
    LDX [NUM_DEST]
    LDAA [DIGIT]
    JSR GLYPH
    LDX [NUM_DEST]
    INX
    STX [NUM_DEST]
    RTS

; Second HUD line uses the same three-digit numeric format as the menus.
RENDER_STATUS_LINE:
    LDX S_STATS
    LDAA FRAMEBUFFER >> 8
    LDAB 32
    JSR TEXT
    LDAA [G_ATTACK]
    LDX FRAMEBUFFER + 36
    JSR NUMBER
    LDAA [G_DEFENSE]
    LDX FRAMEBUFFER + 44
    JSR NUMBER
    LDX FRAMEBUFFER + 55
    JMP RENDER_GOLD
